### ISSUE TITLE
Automatic startup instructions for Raspian

### ISSUE THREAD

**Issue by sikalabsga** [n8henrie/fauxmo#100]
- Issues not following the template may be closed for that reason alone.
- **Operating system and version**:
- **Python version**:
- **Fauxmo version** (`fauxmo --version`):
- **Echo device type** (e.g. Echo, Echo Plus, Dot): 
- **[Echo Firmware Version](https://github.com/n8henrie/fauxmo/blob/dev/README.md#troubleshooting--faq)**: 

## My Issue
I followed the guidelines on autostart of fauxmo server and yet with no luck.
I installed fauxmo via pypi using a virtual environment. In the terminal I'm able to run the fauxmo server without a problem. In the venv/bin folder I created a folder named extras and inside it a file fauxmo.service whose content came from the extras on github. Copied its content to /etc/systemd/system/ and modified the execution path as shown below

```
Description=Fauxmo
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=/home/pi/MyHomeAutomationServer/venv/bin/fauxmo
# Fix the paths below:
ExecStart=/home/pi/MyHomeAutomationServer/venv/bin/fauxmo -c /home/pi/MyHomeAutomationServer/config-alexavoiceswitcherplugin.json
Restart=on-failure
RestartSec=10s
User=fauxmo



[Install]
WantedBy=multi-user.target
```
fauxmo.service                                              loaded activating auto-restart Fauxmo

raspbien os buster
fauxmo v0.5.0
Python 3.7.3

## [WHYT](http://mattgemmell.com/what-have-you-tried)

---

Please make sure you've taken these steps before submitting a new issue:

- [ ] Try to reproduce the issue with Fauxmo installed in a
  [venv](https://docs.python.org/3/library/venv.html)
- [ ] Ensure you're running a supported version of Python
    - Requires Python >= 3.2 for Fauxmo < 0.3.0
    - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
    - Requires Python >= 3.6.0 for Fauxmo >= 0.4.0
- [ ] Run Fauxmo in debug mode (`-vvv`) and include relevant output
- [ ] Include your Fauxmo `config.json`
- [ ] Search the existing (including closed) issues
- [ ] Please use [codeblocks][1] around your debug output and config

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by n8henrie** [comment]
Hello again!

Please try to remember to use codeblocks, as requested in the issue template.

> venv/bin folder I created a folder named extras and inside it a file fauxmo.service whom content came from the extras on github

That's an odd place to put it, but seems unlikely to cause a lot of problems. Sounds like you correctly moved it to the correct location later.

This issue doesn't sound like a Fauxmo problem, but more of a general Linux problem. I'm happy to try to give you some tips, but you might find better support just reading more about systemd service files.

First, I would make sure of your path to Fauxmo. Above, it looks like you have `/home/pi/MyHomeAutomationServer/venv/bin/fauxmo` in your service file.

If you run the command below, does Fauxmo start?

```
/home/pi/MyHomeAutomationServer/venv/bin/fauxmo -c /home/pi/MyHomeAutomationServer/config-alexavoiceswitcherplugin.json
```

Because this is what you've told `systemd` to start.

If that works, you should run `sudo systemctl start fauxmo.service`, and it should run. If that works, `sudo systemctl enable fauxmo.service` and it should start automatically after reboot.

If the command above *doesn't* work, you need to fix it, then change your service file to reflect the correct command.

If the command works, but the service file doesn't, you need to review the `journald` output to try to sort things out: `sudo journalctl -b -u fauxmo.service`.

Hope that helps!

**Comment by sikalabsga** [comment]
Hello again,

Thanks for your time to help me with this issue.
Yes, this command /home/pi/MyHomeAutomationServer/venv/bin/fauxmo -c /home/pi/MyHomeAutomationServer/config-alexavoiceswitcherplugin.json 
manually executes successfully starting the Fauxmo server.

when I run sudo systemctl start fauxmo.service and then sudo systemctl status fauxmo.service I get the following:
● fauxmo.service - Fauxmo
   Loaded: loaded (/etc/systemd/system/fauxmo.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2020-05-23 10:20:00 CDT; 2s ago
  Process: 12708 ExecStart=/home/pi/MyHomeAutomationServer/venv/bin/fauxmo -c /home/pi/MyHomeAutomationServer/config-alexavoiceswitcherplugin.json -v (code=exited, stat
 Main PID: 12708 (code=exited, status=200/CHDIR)
and it doesn't work.

**Comment by sikalabsga** [comment]
And below is the review of the following sudo journalctl -b -u fauxmo.service command
fauxmo.service: Changing to the requested working directory failed: Not a directory
May 23 22:20:44 raspberrypi systemd[12407]: fauxmo.service: Failed at step CHDIR spawning /home/pi/MyHomeAutomationServer/venv/bin/fauxmo: Not a directory

**Comment by sikalabsga** [comment]
In short I have the incorrect working directory in the fauxmo.service file. Any idea what path I should put as the working directory?

**Comment by sikalabsga** [comment]
However, im experience different issue.

(venv) pi@raspberrypi:~/MyHomeAutomationServer $ sudo journalctl -b -u fauxmo.service
-- Logs begin at Sun 2020-05-24 10:54:58 CDT, end at Sun 2020-05-24 12:44:03 CDT. --
May 24 10:55:03 raspberrypi systemd[1]: Started Fauxmo.
May 24 10:55:05 raspberrypi fauxmo[418]: Traceback (most recent call last):
May 24 10:55:05 raspberrypi fauxmo[418]:   File "/home/pi/MyHomeAutomationServer/venv/bin/fauxmo", line 10, in <module>
May 24 10:55:05 raspberrypi fauxmo[418]:     sys.exit(cli())
May 24 10:55:05 raspberrypi fauxmo[418]:   File "/home/pi/MyHomeAutomationServer/venv/lib/python3.7/site-packages/fauxmo/cli.py", line 37, in cli
May 24 10:55:05 raspberrypi fauxmo[418]:     main(config_path_str=args.config, verbosity=verbosity)
May 24 10:55:05 raspberrypi fauxmo[418]:   File "/home/pi/MyHomeAutomationServer/venv/lib/python3.7/site-packages/fauxmo/fauxmo.py", line 65, in main
May 24 10:55:05 raspberrypi fauxmo[418]:     fauxmo_ip = get_local_ip(fauxmo_config.get("ip_address"))
May 24 10:55:05 raspberrypi fauxmo[418]:   File "/home/pi/MyHomeAutomationServer/venv/lib/python3.7/site-packages/fauxmo/utils.py", line 37, in get_local_ip
May 24 10:55:05 raspberrypi fauxmo[418]:     sock.connect(("8.8.8.8", 80))
May 24 10:55:05 raspberrypi fauxmo[418]: OSError: [Errno 101] Network is unreachable
May 24 10:55:06 raspberrypi systemd[1]: fauxmo.service: Main process exited, code=exited, status=1/FAILURE
May 24 10:55:06 raspberrypi systemd[1]: fauxmo.service: Failed with result 'exit-code'.
May 24 10:55:16 raspberrypi systemd[1]: fauxmo.service: Service RestartSec=10s expired, scheduling restart.
May 24 10:55:16 raspberrypi systemd[1]: fauxmo.service: Scheduled restart job, restart counter is at 1.
May 24 10:55:16 raspberrypi systemd[1]: Stopped Fauxmo.
May 24 10:55:16 raspberrypi systemd[1]: Started Fauxmo.
May 24 10:55:16 raspberrypi fauxmo[1176]: Traceback (most recent call last):
May 24 10:55:16 raspberrypi fauxmo[1176]:   File "/home/pi/MyHomeAutomationServer/venv/bin/fauxmo", line 10, in <module>
May 24 10:55:16 raspberrypi fauxmo[1176]:     sys.exit(cli())
May 24 10:55:16 raspberrypi fauxmo[1176]:   File "/home/pi/MyHomeAutomationServer/venv/lib/python3.7/site-packages/fauxmo/cli.py", line 37, in cli
May 24 10:55:16 raspberrypi fauxmo[1176]:     main(config_path_str=args.config, verbosity=verbosity)
May 24 10:55:16 raspberrypi fauxmo[1176]:   File "/home/pi/MyHomeAutomationServer/venv/lib/python3.7/site-packages/fauxmo/fauxmo.py", line 65, in main
May 24 10:55:16 raspberrypi fauxmo[1176]:     fauxmo_ip = get_local_ip(fauxmo_config.get("ip_address"))
May 24 10:55:16 raspberrypi fauxmo[1176]:   File "/home/pi/MyHomeAutomationServer/venv/lib/python3.7/site-packages/fauxmo/utils.py", line 37, in get_local_ip
May 24 10:55:16 raspberrypi fauxmo[1176]:     sock.connect(("8.8.8.8", 80))
May 24 10:55:16 raspberrypi fauxmo[1176]: OSError: [Errno 101] Network is unreachable
May 24 10:55:16 raspberrypi systemd[1]: fauxmo.service: Main process exited, code=exited, status=1/FAILURE
May 24 10:55:16 raspberrypi systemd[1]: fauxmo.service: Failed with result 'exit-code'.
May 24 10:55:27 raspberrypi systemd[1]: fauxmo.service: Service RestartSec=10s expired, scheduling restart.
May 24 10:55:27 raspberrypi systemd[1]: fauxmo.service: Scheduled restart job, restart counter is at 2.
May 24 10:55:27 raspberrypi systemd[1]: Stopped Fauxmo.
May 24 10:55:27 raspberrypi systemd[1]: Started Fauxmo.
May 24 10:55:27 raspberrypi fauxmo[1402]: Traceback (most recent call last):
May 24 10:55:27 raspberrypi fauxmo[1402]:   File "/home/pi/MyHomeAutomationServer/venv/lib/python3.7/site-packages/fauxmo/fauxmo.py", line 95, in main
May 24 10:55:27 raspberrypi fauxmo[1402]:     module = importlib.import_module(modname)
May 24 10:55:27 raspberrypi fauxmo[1402]:   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
May 24 10:55:27 raspberrypi fauxmo[1402]:     return _bootstrap._gcd_import(name[level:], package, level)
May 24 10:55:27 raspberrypi fauxmo[1402]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
May 24 10:55:27 raspberrypi fauxmo[1402]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
May 24 10:55:27 raspberrypi fauxmo[1402]:   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
May 24 10:55:27 raspberrypi fauxmo[1402]: ModuleNotFoundError: No module named 'fauxmo.plugins.alexavoiceswitcherplugin'

**Comment by n8henrie** [comment]
Okay, you have *really* got to start using codeblocks. It is extremely difficult to read your posts without them. Please read about them and use them from now on.

**Comment by n8henrie** [comment]
Now that this issue is resolved I am going to close it.

Feel free to start a new issue for the new problem if you would like, but I need you to follow the issue template in its entirety and include all requested information.

Or you can refer back to the [last issue you started](https://github.com/n8henrie/fauxmo/issues/99) which looks like a similar issue; I didn't entirely understand your explanation in that issue, so I'm not totally sure how you resolved it before.
