### ISSUE TITLE
Support Wemo Dimmer Switch

### ISSUE THREAD

**Issue by mocallins** [n8henrie/fauxmo#104]
Are you looking at adding other Wemo devices that Raspberry Pi would be able to emulate.

I would think the dimmer switch would be an excellent addition, since it has more functions, to play around with.

Thanks in advance.

i.e. somebody else out there has captured the setup.xml

**Comment by n8henrie** [comment]
I am not, since I don't have any relevant devices, so I am both not particularly motivated and moreover would be unable to ensure my implementation worked.

Do you have a link to a reference implementation I could check out? If it fits neatly into the codebase and the contributor were interesting in helping maintain the relevant code going forward, I would accept a PR.

**Comment by mocallins** [comment]
Hmmm i'm not sure if it was a full implementation, i just saw that they had captured the setup.xml

I'll look around again, it was here on github.

**Comment by mocallins** [comment]
Add support for WeMo Dimmer Light Switch #3632

https://github.com/eclipse-archived/smarthome/issues/3632

**Comment by mocallins** [comment]
Also as an aside, looking through some of the code, you ever heard of a script/package out there called xml(2|To)dict  ,lol ?
Just something i found and used in my own testing work (network testing with python), i had done in the past.
Makes dealing with xml data much simpler, can just use normal python commands to interrogate ,  as well as make a response  structure, just as easy with dict(2|To)xml.

**Comment by n8henrie** [comment]
Cool, thanks for the link.

> you ever heard of a script/package out there called xml(2|To)dict ,lol ?

While I can manage Python dependencies pretty easily, unfortunately they end up being difficult to deal with for end users, who then need to work about system vs user installs, virtualenvs, conflicting requirements, etc; as a maintainer, I strongly prefer Fauxmo to remain dependency-free.

https://github.com/n8henrie/fauxmo#plugins

> Any pre-installed plugins, like the rest of the core Fauxmo code, have no third party dependencies.

**Comment by mocallins** [comment]
I understand, I basically took over the package and supported it withihn my librariesx, for pretty much the same reason, i think  I found another version of it that someone claimed we needed, but really didn't.So i ended tht discussion by including it, lol
Even though it is a package, its not very extensive, that's why i really refer to it as a script.And well afterword its just a part of the library, and internally maintained, lol.


    On Saturday, August 29, 2020, 9:55:39 AM CDT, Nathan Henrie <notifications@github.com> wrote:  
 
 


Cool, thanks for the link.


you ever heard of a script/package out there called xml(2|To)dict ,lol ?


While I can manage Python dependencies pretty easily, unfortunately they end up being difficult to deal with for end users, who then need to work about system vs user installs, virtualenvs, conflicting requirements, etc; as a maintainer, I strongly prefer Fauxmo to remain dependency-free.

https://github.com/n8henrie/fauxmo#plugins


Any pre-installed plugins, like the rest of the core Fauxmo code, have no third party dependencies.
