### ISSUE TITLE
Emulate TV

### ISSUE THREAD

**Issue by Bobsilvio** [n8henrie/fauxmo#106]
Hello I have recently been approaching alexa.
I created a skill (name = mediaserver control) for a mediaserver (linux) that I have at home, with internal API to call the commands http://192.168.178.100/api/switchon.
Alexa ask mediaserver control turn on (turn off) Mediaserver
Alexa ask mediaserver control to change channel on 6 (http://192.168.178.100/api/switchannel=6)
and other commands
Alexa doesn't read local IPs, so you have to use DNS. I was looking for a solution to emulate the mediaserver from linux like a TV to pass commands directly without using DNS (which needs to open ports) and also to launch commands like
Alexa turn on mediaserver
alexa changes the channel of the media server on 9

Is Fauxmo the right solution for me?
I've tested the recognition and it works, but sees it as a catch.
Do you know similar solutions? thank you

**Comment by n8henrie** [comment]
I'm not sure what you mean about DNS. Fauxmo would definitely be able to make **some** of those API calls locally.

> Is Fauxmo the right solution for me?

I don't think so. It is limited to `alexa turn on [device name]` or `alexa turn off [device name]`, I don't know of a good way to implement changing channels. You may be able to find a workaround with Routines, but I'll leave that investigation up to you.
