### ISSUE TITLE
Running fauxmo with hundreds of devices

### ISSUE THREAD

**Issue by neodesc** [n8henrie/fauxmo#112]
- Issues not following the template may be closed for that reason alone.
- **Operating system and version**: Raspbian GNU/Linux 11 \n \l
- **Python version**: Python 3.9.2
- **Fauxmo version** (`fauxmo --version`): v0.5.2
- **Echo device type** (e.g. Echo, Echo Plus, Dot): Dot
- **[Echo Firmware Version](https://github.com/n8henrie/fauxmo/blob/dev/README.md#troubleshooting--faq)**: 6409852036

## My Issue

I've been running fauxmo with the command line plugin for a couple of years now with no issues. However I'm adding a lot more devices (~250) in the config.json file now and its not working anymore: device unresponsive. The Echo discovers them correctly but it just can't use them most of the time.

## [WHYT](http://mattgemmell.com/what-have-you-tried)

Reducing my list of devices. Managed to get it from over 900 to ~250.
It works great with 50 but I need 250 because my KNX devices are not alexa compatible and I need a "commandline device" for each real device property. For instance a blind has 10 positions + its slates.

---

Please make sure you've taken these steps before submitting a new issue:

- [ ] Try to reproduce the issue with Fauxmo installed in a
  [venv](https://docs.python.org/3/library/venv.html)
- [ ] Ensure you're running a supported version of Python
    - Requires Python >= 3.2 for Fauxmo < 0.3.0
    - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
    - Requires Python >= 3.6.0 for Fauxmo >= 0.4.0
- [ ] Run Fauxmo in debug mode (`-vvv`) and include relevant output
- [ ] Include your Fauxmo `config.json`
- [ ] Search the existing (including closed) issues
- [ ] Please use [codeblocks][1] around your debug output and config

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by n8henrie** [comment]
Wow!

I'm blown away that you're using this with so many devices.

I'll need to think about it, but honestly this part makes me think it might be an issue on the Echo side (emphasis mine):

> The Echo discovers them correctly but it just can't use them **most of the time.**

Because fauxmo is all asyncio based, I would think it could handle hundreds of devices without issue.

I'll almost certainly need some debug output. Can you capture and post a verbose / debug log during a failed attempt to trigger a device?

**Comment by n8henrie** [comment]
@neodesc You might try the dev branch; I've added a few lines to support running on [`uvloop`](https://github.com/MagicStack/uvloop), which has much better performance than the built-in event loop. It *might* make a difference in your case of being able to handle hundreds of devices.

```console
$ source venv/bin/activate
$ python -m pip install uvloop
$ python -m pip install git+git://github.com/n8henrie/fauxmo.git@dev
```

**Comment by neodesc** [comment]
Hi Nathan,

I’ve been using your regular main code. Figured out as long as I have less
than 200 devices everything works just fine.

I’ll keep the dev branch in mind though for possible future setups. Thank
you very much for your help :)
