### ISSUE TITLE
HA plugin, device not responding

### ISSUE THREAD

**Issue by redakker** [n8henrie/fauxmo#114]
Fauxmo is running in docker container: https://github.com/ServerContainers/fauxmo
Operating system is Linux
Python version is what is in the continer, python3 
- v0.5.0
- echo dot: 673727120

## My Issue
I have a humidifier, which can be switched on/off by homeassistant, but somehow I cannot control it with fauxmo.
I can control switch type switches only.

I did some experiment with the API:

/api/services/homeassistant/turn_on | {"entity_id":"switch.kitchen_switch"} WORKING
/api/services/homeassistant/turn_on | {"entity_id":"humidifier.humdevice"} WORKING

/api/services/switch/turn_on | {"entity_id":"switch.kitchen_switch"} WORKING
/api/services/switch/turn_on | {"entity_id":"humidifier.humdevice"} NOT_WORKING

My question is which service is used in fauxmo? switch or homeassistant? I've tried to browse the code, but I'm not sure.
If "homeassistant" service is used in then I investigate further.
Alexa cannot see this device to switch with the humidifier entity_id. If I change the config (same name/port) to a switch type, then everything is okay.

Thank you for your answer, and thank you for this awesome project.

**Comment by redakker** [comment]
I thing I found the issue.
The code tries to find out the service from the entity domain
light.device -> /api/services/light/turn_on
switch.device -> /api/services/switch/turn_on

But in my case the domain is not a service, but the device itself.
Can I directly tell to fauxmo, use the service "homeassistant" to turn on/off the device?

**Comment by n8henrie** [comment]
You're right, I should reveal `domain` as an optional config parameter (I've done a little workaround for `group` to allow it to work with `homeassistant.turn_on`: <https://github.com/n8henrie/fauxmo/blob/master/src/fauxmo/plugins/homeassistantplugin.py#L103>).

Until I get around to this, you could probably use either https://github.com/n8henrie/fauxmo/blob/master/src/fauxmo/plugins/simplehttpplugin.py or (if that doesn't work) https://github.com/n8henrie/fauxmo-plugins/blob/master/restapiplugin.py to translate it into an http-based API call.

**Comment by redakker** [comment]
@n8henrie 

Thank you so much! I'll wait for the fix, fortunately, it is not highly urgent. :)
Thank you for your work. Awesome!

**Comment by n8henrie** [comment]
@redakker Can you try the current dev branch? `python -m pip install git+git://github.com/n8henrie/fauxmo.git@dev`

It should allow you to configure a `domain` key in `config.json`.

**Comment by redakker** [comment]
@n8henrie Thank you, I take look soon.
But I've quickly checked the code, it should work.
I come back to you with the test result.

**Comment by redakker** [comment]
@n8henrie It works in a dev branch, thank you for your effort!
You can close the ticket.
