### ISSUE TITLE
Any way to start at boot?

### ISSUE THREAD

**Issue by karl0ss** [n8henrie/fauxmo#17]
Great work on your extension, I have this running perfectly on my raspberry pi...

But I want to get it to start at boot...I have made a cron job, but it doesn't seem to be working..

""$(pyenv root)"/versions/3.5.1/bin/fauxmo -c /home/pi/config.json -vvv" 

Works fine when I run from the command line, but not from the cronjob..

Any idea? -  I believe I have just seen the answer on your readme, so I will try that..

**Comment by karl0ss** [comment]
Got this working using the direct path, not $(pyenv root) in my cron job...it works fine now :)

**Comment by n8henrie** [comment]
Glad you got it running. If you're running Raspbian Jessie, I recommend the systemd service file I [mention in the readme](https://github.com/n8henrie/fauxmo#systemd-eg-raspbian-jessie) (I placed a copy in  `extras/`).
