### ISSUE TITLE
install fails with compile errors

### ISSUE THREAD

**Issue by bill-orange** [n8henrie/fauxmo#23]
- **Operating system and version**:
Raspian Jessie on Raspberry PI 3
- **Python version**:
Python 3.4.2 (default, Oct 19 2014, 13:31:11) 
- **Fauxmo version**:
Latest (0.3.6)?

## My Issue

Install fails when running:  python3 -m pip install fauxmo

## [WHYT](http://mattgemmell.com/what-have-you-tried)

Tried twice one without sudo and one with.  compile errors were generated as shown below:

pi@raspberrypi:~ $ sudo su
root@raspberrypi:/home/pi# python3 -m pip install fauxmo
Downloading/unpacking fauxmo
  Downloading fauxmo-0.3.6-py3-none-any.whl
Downloading/unpacking requests==2.12.4 (from fauxmo)
  Downloading requests-2.12.4-py2.py3-none-any.whl (576kB): 576kB downloaded
Downloading/unpacking homeassistant==0.31.1 (from fauxmo)
  Downloading homeassistant-0.31.1-py2.py3-none-any.whl (6.4MB): 6.4MB downloaded
Downloading/unpacking pip>=7.0.0 (from homeassistant==0.31.1->fauxmo)
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Downloading/unpacking pytz>=2016.6.1 (from homeassistant==0.31.1->fauxmo)
  Downloading pytz-2016.10-py2.py3-none-any.whl (483kB): 483kB downloaded
Downloading/unpacking pyyaml>=3.11,<4 (from homeassistant==0.31.1->fauxmo)
  Downloading PyYAML-3.12.tar.gz (253kB): 253kB downloaded
  Running setup.py (path:/tmp/pip-build-0my8jj1z/pyyaml/setup.py) egg_info for package pyyaml
    
Downloading/unpacking jinja2>=2.8 (from homeassistant==0.31.1->fauxmo)
  Downloading Jinja2-2.9.5-py2.py3-none-any.whl (340kB): 340kB downloaded
Downloading/unpacking voluptuous==0.9.2 (from homeassistant==0.31.1->fauxmo)
  Downloading voluptuous-0.9.2.tar.gz
  Running setup.py (path:/tmp/pip-build-0my8jj1z/voluptuous/setup.py) egg_info for package voluptuous
    WARNING: Could not locate pandoc, using Markdown long_description.
    
Downloading/unpacking typing>=3,<4 (from homeassistant==0.31.1->fauxmo)
  Downloading typing-3.5.3.0.tar.gz (60kB): 60kB downloaded
  Running setup.py (path:/tmp/pip-build-0my8jj1z/typing/setup.py) egg_info for package typing
    
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from jinja2>=2.8->homeassistant==0.31.1->fauxmo)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=0.6b1 in /usr/lib/python3/dist-packages (from voluptuous==0.9.2->homeassistant==0.31.1->fauxmo)
Installing collected packages: fauxmo, requests, homeassistant, pip, pytz, pyyaml, jinja2, voluptuous, typing
  Found existing installation: requests 2.4.3
    Not uninstalling requests at /usr/lib/python3/dist-packages, owned by OS
  Found existing installation: pip 1.5.6
    Not uninstalling pip at /usr/lib/python3/dist-packages, owned by OS
  Running setup.py install for pyyaml
    checking if libyaml is compilable
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c build/temp.linux-armv7l-3.4/check_libyaml.c -o build/temp.linux-armv7l-3.4/check_libyaml.o
    build/temp.linux-armv7l-3.4/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
     #include <yaml.h>
                      ^
    compilation terminated.
    
    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)
    
  Found existing installation: Jinja2 2.7.3
    Not uninstalling Jinja2 at /usr/lib/python3/dist-packages, owned by OS
*** Error compiling '/tmp/pip-build-0my8jj1z/jinja2/jinja2/asyncfilters.py'...
  File "/tmp/pip-build-0my8jj1z/jinja2/jinja2/asyncfilters.py", line 7
    async def auto_to_seq(value):
            ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip-build-0my8jj1z/jinja2/jinja2/asyncsupport.py'...
  File "/tmp/pip-build-0my8jj1z/jinja2/jinja2/asyncsupport.py", line 22
    async def concat_async(async_gen):
            ^
SyntaxError: invalid syntax

  Running setup.py install for voluptuous
    WARNING: Could not locate pandoc, using Markdown long_description.
    
  Running setup.py install for typing
    
Successfully installed fauxmo requests homeassistant pip pytz pyyaml jinja2 voluptuous typing
Cleaning up...
root@raspberrypi:/home/pi# 

---

Please make sure you've taken these steps before submitting a new issue:

- [ ] Include the Python and Fauxmo version in your issue
- [ ] Ensure you're running a supported version of Python
    - Requires Python >= 3.2 for Fauxmo < 0.3.0
    - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
- [ ] Run Fauxmo in debug mode (`-vvv`) and include relevant output
- [ ] Search the existing (and closed) issues

**Comment by n8henrie** [comment]
Huh. I *highly* recommend installing into a virtualenv to avoid having to use root and to avoid problems with the system installation. Please try again with a virtualenv.

```shell_session
$ mkdir -p fauxmo
$ cd fauxmo
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install --upgrade fauxmo
```

If you get an error about not having `venv` you may need to install it manually (it may not have come with 3.4 IIRC), something like `sudo apt-get install python3.4-venv` or something like that.

**Comment by bill-orange** [comment]
good Idea

I did have to install venv but I got roughly the same errors

Before we try to troubleshoot this any more.  I will burn a clean new uSD with the latest Raspian and see what happens.  Maybe there is a conflict with something else on this machine.  I will report back tomorrow.

pip install --upgrade fauxmo
Downloading/unpacking fauxmo
  Downloading fauxmo-0.3.6-py3-none-any.whl
Downloading/unpacking homeassistant==0.31.1 (from fauxmo)
  Downloading homeassistant-0.31.1-py2.py3-none-any.whl (6.4MB): 6.4MB downloaded
Downloading/unpacking requests==2.12.4 (from fauxmo)
  Downloading requests-2.12.4-py2.py3-none-any.whl (576kB): 576kB downloaded
Downloading/unpacking pyyaml>=3.11,<4 (from homeassistant==0.31.1->fauxmo)
  Downloading PyYAML-3.12.tar.gz (253kB): 253kB downloaded
  Running setup.py (path:/tmp/pip-build-gnpdb_ic/pyyaml/setup.py) egg_info for package pyyaml
    
Downloading/unpacking voluptuous==0.9.2 (from homeassistant==0.31.1->fauxmo)
  Downloading voluptuous-0.9.2.tar.gz
  Running setup.py (path:/tmp/pip-build-gnpdb_ic/voluptuous/setup.py) egg_info for package voluptuous
    WARNING: Could not locate pandoc, using Markdown long_description.
    
Downloading/unpacking pip>=7.0.0 (from homeassistant==0.31.1->fauxmo)
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Downloading/unpacking jinja2>=2.8 (from homeassistant==0.31.1->fauxmo)
  Downloading Jinja2-2.9.5-py2.py3-none-any.whl (340kB): 340kB downloaded
Downloading/unpacking pytz>=2016.6.1 (from homeassistant==0.31.1->fauxmo)
  Downloading pytz-2016.10-py2.py3-none-any.whl (483kB): 483kB downloaded
Downloading/unpacking typing>=3,<4 (from homeassistant==0.31.1->fauxmo)
  Downloading typing-3.5.3.0.tar.gz (60kB): 60kB downloaded
  Running setup.py (path:/tmp/pip-build-gnpdb_ic/typing/setup.py) egg_info for package typing
    
Downloading/unpacking setuptools>=0.6b1 from https://pypi.python.org/packages/49/09/68b43c68492a9d437c137892d11427ac45a1497812c8a8ce2cd17649a27c/setuptools-34.3.1-py2.py3-none-any.whl#md5=ea9c9c51767f5037754dc6228cdeb607 (from voluptuous==0.9.2->homeassistant==0.31.1->fauxmo)
  Downloading setuptools-34.3.1-py2.py3-none-any.whl (389kB): 389kB downloaded
Downloading/unpacking MarkupSafe>=0.23 (from jinja2>=2.8->homeassistant==0.31.1->fauxmo)
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py (path:/tmp/pip-build-gnpdb_ic/MarkupSafe/setup.py) egg_info for package MarkupSafe
    
Downloading/unpacking packaging>=16.8 (from setuptools>=0.6b1->voluptuous==0.9.2->homeassistant==0.31.1->fauxmo)
  Downloading packaging-16.8-py2.py3-none-any.whl
Downloading/unpacking appdirs>=1.4.0 (from setuptools>=0.6b1->voluptuous==0.9.2->homeassistant==0.31.1->fauxmo)
  Downloading appdirs-1.4.2-py2.py3-none-any.whl
Downloading/unpacking six>=1.6.0 (from setuptools>=0.6b1->voluptuous==0.9.2->homeassistant==0.31.1->fauxmo)
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking pyparsing (from packaging>=16.8->setuptools>=0.6b1->voluptuous==0.9.2->homeassistant==0.31.1->fauxmo)
  Downloading pyparsing-2.1.10-py2.py3-none-any.whl (56kB): 56kB downloaded
Installing collected packages: fauxmo, homeassistant, requests, pyyaml, voluptuous, pip, jinja2, pytz, typing, setuptools, MarkupSafe, packaging, appdirs, six, pyparsing
  Running setup.py install for pyyaml
    checking if libyaml is compilable
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/home/pi/fauxmo/venv/include -I/usr/include/python3.4m -c build/temp.linux-armv7l-3.4/check_libyaml.c -o build/temp.linux-armv7l-3.4/check_libyaml.o
    build/temp.linux-armv7l-3.4/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
     #include <yaml.h>
                      ^
    compilation terminated.
    
    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)
    
  Running setup.py install for voluptuous
    WARNING: Could not locate pandoc, using Markdown long_description.
    
  Found existing installation: pip 1.5.6
    Uninstalling pip:
      Successfully uninstalled pip
*** Error compiling '/tmp/pip-build-gnpdb_ic/jinja2/jinja2/asyncfilters.py'...
  File "/tmp/pip-build-gnpdb_ic/jinja2/jinja2/asyncfilters.py", line 7
    async def auto_to_seq(value):
            ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip-build-gnpdb_ic/jinja2/jinja2/asyncsupport.py'...
  File "/tmp/pip-build-gnpdb_ic/jinja2/jinja2/asyncsupport.py", line 22
    async def concat_async(async_gen):
            ^
SyntaxError: invalid syntax

  Running setup.py install for typing
    
  Found existing installation: setuptools 5.5.1
    Uninstalling setuptools:
      Successfully uninstalled setuptools
  Running setup.py install for MarkupSafe
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/pi/fauxmo/venv/lib/python3.4/site-packages/setuptools/__init__.py", line 10, in <module>
        from six.moves import filter, map
    ImportError: No module named 'six'
    Complete output from command /home/pi/fauxmo/venv/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-gnpdb_ic/MarkupSafe/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-6znztiv7-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/fauxmo/venv/include/site/python3.4:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/pi/fauxmo/venv/lib/python3.4/site-packages/setuptools/__init__.py", line 10, in <module>

    from six.moves import filter, map

ImportError: No module named 'six'

----------------------------------------
Cleaning up...
Command /home/pi/fauxmo/venv/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-gnpdb_ic/MarkupSafe/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-6znztiv7-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/fauxmo/venv/include/site/python3.4 failed with error code 1 in /tmp/pip-build-gnpdb_ic/MarkupSafe
Storing debug log for failure in /home/pi/.pip/pip.log
(venv) pi@raspberrypi:~/fauxmo $

**Comment by bill-orange** [comment]
Well.  That took less time than I expected.  I trued again using a fresh uSD and a clean, new install of 3-2-17 Jessie.  Same errors.

*** Error compiling '/tmp/pip-build-wstwk99o/jinja2/jinja2/asyncfilters.py'...
  File "/tmp/pip-build-wstwk99o/jinja2/jinja2/asyncfilters.py", line 7
    async def auto_to_seq(value):
            ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip-build-wstwk99o/jinja2/jinja2/asyncsupport.py'...
  File "/tmp/pip-build-wstwk99o/jinja2/jinja2/asyncsupport.py", line 22
    async def concat_async(async_gen):
            ^
SyntaxError: invalid syntax

  Running setup.py install for voluptuous
    WARNING: Could not locate pandoc, using Markdown long_description.
    
  Running setup.py install for pyyaml
    checking if libyaml is compilable
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/home/pi/fauxmo/venv/include -I/usr/include/python3.4m -c build/temp.linux-armv7l-3.4/check_libyaml.c -o build/temp.linux-armv7l-3.4/check_libyaml.o
    build/temp.linux-armv7l-3.4/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
     #include <yaml.h>
                      ^
    compilation terminated.
    
    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)

**Comment by n8henrie** [comment]
Hmmmm... looks like part of the message [may be related to pip being outdated](https://github.com/pallets/jinja/issues/643), so try `pip install --upgrade pip` first. May require `sudo` if you're doing it globally, should not require if you're doing it in your `venv`.

Can you do this and update? I'm still Googling why you're getting that yaml error -- sounds like it should fall back to a pure python implementation if the compilation fails, but instead it's just failing outright...

**Comment by bill-orange** [comment]
Just to avoid any 'wildcards', I started with a clean install and got the same error after updating pip.

root@raspberrypi:/home/pi# pip install --upgrade pip
Downloading/unpacking pip from https://pypi.python.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl#md5=297dbd16ef53bcef0447d245815f5144
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.6
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed pip
Cleaning up...
root@raspberrypi:/home/pi# python3 -m pip install fauxmo
Downloading/unpacking fauxmo
  Downloading fauxmo-0.3.6-py3-none-any.whl
Downloading/unpacking requests==2.12.4 (from fauxmo)
  Downloading requests-2.12.4-py2.py3-none-any.whl (576kB): 576kB downloaded
Downloading/unpacking homeassistant==0.31.1 (from fauxmo)
  Downloading homeassistant-0.31.1-py2.py3-none-any.whl (6.4MB): 6.4MB downloaded
Downloading/unpacking pip>=7.0.0 (from homeassistant==0.31.1->fauxmo)
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Downloading/unpacking voluptuous==0.9.2 (from homeassistant==0.31.1->fauxmo)
  Downloading voluptuous-0.9.2.tar.gz
  Running setup.py (path:/tmp/pip-build-slk3yzu_/voluptuous/setup.py) egg_info for package voluptuous
    WARNING: Could not locate pandoc, using Markdown long_description.
    
Downloading/unpacking pytz>=2016.6.1 (from homeassistant==0.31.1->fauxmo)
  Downloading pytz-2016.10-py2.py3-none-any.whl (483kB): 483kB downloaded
Downloading/unpacking pyyaml>=3.11,<4 (from homeassistant==0.31.1->fauxmo)
  Downloading PyYAML-3.12.tar.gz (253kB): 253kB downloaded
  Running setup.py (path:/tmp/pip-build-slk3yzu_/pyyaml/setup.py) egg_info for package pyyaml
    
Downloading/unpacking jinja2>=2.8 (from homeassistant==0.31.1->fauxmo)
  Downloading Jinja2-2.9.5-py2.py3-none-any.whl (340kB): 340kB downloaded
Downloading/unpacking typing>=3,<4 (from homeassistant==0.31.1->fauxmo)
  Downloading typing-3.5.3.0.tar.gz (60kB): 60kB downloaded
  Running setup.py (path:/tmp/pip-build-slk3yzu_/typing/setup.py) egg_info for package typing
    
Requirement already satisfied (use --upgrade to upgrade): setuptools>=0.6b1 in /usr/lib/python3/dist-packages (from voluptuous==0.9.2->homeassistant==0.31.1->fauxmo)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from jinja2>=2.8->homeassistant==0.31.1->fauxmo)
Installing collected packages: fauxmo, requests, homeassistant, pip, voluptuous, pytz, pyyaml, jinja2, typing
  Found existing installation: requests 2.4.3
    Not uninstalling requests at /usr/lib/python3/dist-packages, owned by OS
  Found existing installation: pip 1.5.6
    Not uninstalling pip at /usr/lib/python3/dist-packages, owned by OS
  Running setup.py install for voluptuous
    WARNING: Could not locate pandoc, using Markdown long_description.
    
  Running setup.py install for pyyaml
    checking if libyaml is compilable
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c build/temp.linux-armv7l-3.4/check_libyaml.c -o build/temp.linux-armv7l-3.4/check_libyaml.o
    build/temp.linux-armv7l-3.4/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
     #include <yaml.h>
                      ^
    compilation terminated.
    
    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)
    
  Found existing installation: Jinja2 2.7.3
    Not uninstalling Jinja2 at /usr/lib/python3/dist-packages, owned by OS
*** Error compiling '/tmp/pip-build-slk3yzu_/jinja2/jinja2/asyncfilters.py'...
  File "/tmp/pip-build-slk3yzu_/jinja2/jinja2/asyncfilters.py", line 7
    async def auto_to_seq(value):
            ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip-build-slk3yzu_/jinja2/jinja2/asyncsupport.py'...
  File "/tmp/pip-build-slk3yzu_/jinja2/jinja2/asyncsupport.py", line 22
    async def concat_async(async_gen):
            ^
SyntaxError: invalid syntax

  Running setup.py install for typing
    
Successfully installed fauxmo requests homeassistant pip voluptuous pytz pyyaml jinja2 typing
Cleaning up...
root@raspberrypi:/home/pi#

**Comment by n8henrie** [comment]
No, I think it actually worked in that last case, look at the 3rd to last line.

> Successfully installed fauxmo requests homeassistant pip voluptuous pytz pyyaml jinja2 typing

Try `venv/bin/fauxmo -vv` and see what happens.

I think you're seeing a warning that you can ignore about yaml -- my understanding is it's faster if you have `libyaml` installed, so it tries to compile and use those C bindings first, but if they're not installed, it falls back to Python. That's why it continues after those yaml errors, they're just warnings.

I think the stuff about Jinja is because you're using Python 3.4 instead of 3.5 - they relatively new Jinja async stuff uses the `async def` keyword, which wasn't introduced until 3.5.

Regardless, it looks like it thinks the installation succeeded in that last case -- I think the combination of ensuring you're using an updated `pip` and using a `venv` may be reasonable to add to the FAQ / troubleshooting section.

EDIT: While trying to figure out what piece of the puzzle made the difference, I just saw that your very first output actually appears to have succeeded as well: 

```shell_session
Successfully installed fauxmo requests homeassistant pip pytz pyyaml jinja2 voluptuous typing
Cleaning up...
root@raspberrypi:/home/pi#
```

So maybe all of this was unnecessary. Can you see if fauxmo works?

**Comment by bill-orange** [comment]
Super. Thanks! A couple more question.  
Where exactly does the config file go using the non-venv install?
What edits do I need to make to the config file for the it to run enough so the Echo "sees" the PI?  I want to be sure that I have gotten that far before I start setting up config for real.
