### ISSUE TITLE
Errors after start fauxmo.py

### ISSUE THREAD

**Issue by Gelezako** [n8henrie/fauxmo#29]
- **Operating system and version**: Windows 10 x64
- **Python version**:  Python 3.6.0 :: Anaconda custom (64-bit)
- **Fauxmo version** (`fauxmo --version`): v0.4.4

## My Issue
I can run the file without error, but Alexa does not find any new devices. What can I do to find out the cause of the problem? Thanks.

## [WHYT](http://mattgemmell.com/what-have-you-tried)

---

Please make sure you've taken these steps before submitting a new issue:

- [x] Try to reproduce the issue with Fauxmo installed in a
  [venv](https://docs.python.org/3/library/venv.html)
- [x] Ensure you're running a supported version of Python
    - Requires Python >= 3.2 for Fauxmo < 0.3.0
    - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
    - Requires Python >= 3.6.0 for Fauxmo >= 0.4.0
- [x] Run Fauxmo in debug mode (`-vvv`) and include relevant output
- [x] Include your Fauxmo `config.json`
- [x] Search the existing (including closed) issues

**Comment by n8henrie** [comment]
From the issue template:

> Run Fauxmo in debug mode (-vvv) and include relevant output

**Comment by Gelezako** [comment]
Hi **Nathan**, thanks for the answer!

I get this error again :(

```
Traceback (most recent call last):
  File "C:\Users\Shred\venv\Lib\site-packages\fauxmo\fauxmo.py", line 17, in <module>
    from fauxmo import __version__, logger
  File "C:\Users\Shred\venv\Lib\site-packages\fauxmo\fauxmo.py", line 17, in <module>
    from fauxmo import __version__, logger
ImportError: cannot import name '__version__'
```

**Comment by n8henrie** [comment]
>>Run Fauxmo in debug mode (-vvv) and include relevant output
Include your Fauxmo config.json

I haven't seen this error before. Please include the requested info so I can try to help.

If the above is the output when running in debug mode, please include the command you're running to start Fauxmo that produces that error.

And as stated I need your config. Make sure to remove any passwords or sensitive info first.

**Comment by Gelezako** [comment]
> I haven't seen this error before. Please include the requested info so I can try to help.

how?

> If the above is the output when running in debug mode, please include the command you're running to start Fauxmo that produces that error.

screen shot:
https://2.bp.blogspot.com/-QGb2u12MK2U/Wc6J_J-tjkI/AAAAAAAAfL8/GcNXsYPkWKIRmgJnlATv2jwWLwS165QwwCLcBGAs/s1600/Untitled.png

> And as stated I need your config. Make sure to remove any passwords or sensitive info first.

I use the default config - config-sample.json

**Comment by n8henrie** [comment]
You're not running it correctly. You're not supposed to run `fauxmo.py` directly, the `setup.py` installs a console script named `fauxmo`. I don't know where that installs on Windows, but I assume it would be in your path, so just try `fauxmo -c config-sample.json` instead of `/path/to/fauxmo.py -c`...

Let me know when you get that working.

**Comment by Gelezako** [comment]
Is this a successful launch?
Screenshot: https://3.bp.blogspot.com/-bHXFSup5c_8/WdNVq57cvFI/AAAAAAAAfNo/xKyi8mCjtXoWTj0iE6-9_Zxj4ZvmbuIQgCLcBGAs/s1600/scr.png

After that, I followed this instruction:

> Open the Amazon Alexa webapp to the Smart Home page
> With Fauxmo running, click "Discover devices" 

, but unfortunately no new Fauxmo devices were found.

Most likely I need to edit the config file, but I do not understand what it is for the IP address - "http://192.168.1.104".
 Is this the local IP address of the computer where I run the Fauxmo script?

**Comment by n8henrie** [comment]
Yes, that is a successful launch.

You should be able to see some fake devices added to your Alexa app if you use the sample config. If they are not being added, something is wrong.

In the future, please copy and paste your output as text, not as screenshots.

Please see the [configuration section of the readme](https://github.com/n8henrie/fauxmo#configuration) if you don't understand the config, I think I've explained it fairly well.

**Comment by Gelezako** [comment]
Do I need to have an account in Belkin WeMo and to install skills from Belkin WeMo?

**Comment by n8henrie** [comment]
Nope

**Comment by Gelezako** [comment]
ok,thanks
