### ISSUE TITLE
Help with Config.json

### ISSUE THREAD

**Issue by REHolt** [n8henrie/fauxmo#34]
- **Operating system and version**: Raspian Linux ver8
- **Python Version**: 3.6.1
- **Fauxmo version** (`fauxmo --version`): 0.4.4

## My Issue
I updated to your latest version of Fauxmo, along with Python 3.6.1. I am trying to set up my devices but am having an issue figuring out the config.json format and was hoping someone would be kind enough to help me figure out the entries I need.

I am using home built ESP8266 devices, they all worked with the old version of Fauxmo from MakerMusing. I can access them via my cell phone app and Alexa will "Discover" the entries, but gives me a "Not responding" message with each.

## [WHYT](http://mattgemmell.com/what-have-you-tried)
My original Fauxmo entries were:

 ['couch lamp', rest_api_handler('http://196.163.1.128/gpio/1', 'http://196.163.1.128/gpio/0')],
 ['garage door', rest_api_handler('http://196.163.1.132/gpio/1', 'http://196.163.1.132/gpio/0')],
 ['Universal Garage Door', rest_api_handler('http://196.163.1.120/gpio/1', 'http://196.163.1.120/gpio/0')],

 ['garage light', rest_api_handler('http://196.163.1.TBD/gpio/1', 'http://196.163.1.TBD/gpio/0')],
 ['christmas lights', rest_api_handler('http://196.163.1.131/gpio/1', 'http://196.163.1.131/gpio/0')],
  
 I have tried several different formats for the config.json including the below:
```json
{
                    "port": 12340,
                    "on_cmd": "http://196.163.1.120/gpio/0",
                    "off_cmd": "http://196.163.1.120/gpio/1",
                    "method": "GET",
                    "name": "Garage Door"
                },
                {
                    "port": 12341,
                    "on_cmd": "http://localhost:54321/devices/garage%20door",
                    "off_cmd": "http://localhost:54321/devices/garage%20door",
                    "on_data": {"isOn": 1},
                    "off_data": {"isOn": 0},
                    "user": "this",
                    "password": "that",
                    "method": "PUT",
                    "name": "fake Indigo switch"
                },
                {
                    "name": "Couch Lamp",
                    "port": 12342,
                  "on_cmd": "http://196.163.1.128:8123/api/services/switch/turn_on",
                    "off_cmd": "http://196.163.1.128:8123/api/services/switch/turn_off",
                    
                    "method": "POST",
                    "headers": {"x-ha-access": "your_hass_password"},
                    "on_data": {"couch lamp": "switch.couch_lamp"},
                    "off_data": {"couch": "switch.couch_lamp"}
                }
```

But I get the same result with each. Below is the debug output:
 File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/site-packages/fauxmo/protocols.py", line 55, in data_received
    self.handle_action(msg)
  File "/usr/local/lib/python3.6/site-packages/fauxmo/protocols.py", line 103, in handle_action
    success = self.plugin.on()
  File "/usr/local/lib/python3.6/site-packages/fauxmo/plugins/simplehttpplugin.py", line 100, in set_state
    with self.urlopen(req) as resp:
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

  I know this should be easy but I'm not really much of a software person. 

Any Help would be greatly appreciated.

Please make sure you've taken these steps before submitting a new issue:

- [ ] Try to reproduce the issue with Fauxmo installed in a
  [venv](https://docs.python.org/3/library/venv.html)
- [ ] Ensure you're running a supported version of Python
    - Requires Python >= 3.2 for Fauxmo < 0.3.0
    - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
    - Requires Python >= 3.6.0 for Fauxmo >= 0.4.0
- [ ] Run Fauxmo in debug mode (`-vvv`) and include relevant output
- [ ] Include your Fauxmo `config.json`
- [ ] Search the existing (including closed) issues

**Comment by n8henrie** [comment]
Thanks for the thorough and complete issue.

That config doesn't look right -- for example

```
['garage door', rest_api_handler('http://196.163.1.132/gpio/1', 'http://196.163.1.132/gpio/0')],
```

vs

```
{
                    "port": 12340,
                    "on_cmd": "http://196.163.1.120/gpio/0",
                    "off_cmd": "http://196.163.1.120/gpio/1",
                    "method": "GET",
                    "name": "Garage Door"
                },
```

^^ The IP address doesn't match between these two.

```
['couch lamp', rest_api_handler('http://196.163.1.128/gpio/1', 'http://196.163.1.128/gpio/0')],
```

```
{
                    "name": "Couch Lamp",
                    "port": 12342,
                  "on_cmd": "http://196.163.1.128:8123/api/services/switch/turn_on",
                    "off_cmd": "http://196.163.1.128:8123/api/services/switch/turn_off",
                    
                    "method": "POST",
                    "headers": {"x-ha-access": "your_hass_password"},
                    "on_data": {"couch lamp": "switch.couch_lamp"},
                    "off_data": {"couch": "switch.couch_lamp"}
                }
```

The IP matches, but the port doesn't match between these.

If `['couch lamp', rest_api_handler('http://196.163.1.128/gpio/1', 'http://196.163.1.128/gpio/0')],` works, I would think that devices would end up like:

```
{
    "name": "Couch Lamp",
    "port": 12342,
    "on_cmd": "http://196.163.1.128/gpio/1",
    "off_cmd": "http://196.163.1.128/gpio/0",
}
```

Can you give that a shot?

**Comment by REHolt** [comment]
Good catch; although that wasn't the issue. I had changed some of the IP addresses in a misguided attempt at security. In the actual file they were OK

 I did some further tinkering and discovered that i actually had the one of the entries correct, but needed to go to the Alexa app and have it forget all of my devices and re-discover them. using the following config.json entries, I now have two of my devices working. I will no go through and fix the remaining devices.

Thanks for the quick response anyway!!

Robert

**Comment by REHolt** [comment]
I do have one other issue you might help with. Now, when I "Discover Devices" everything gets turned on. If this were to happen following a power reset, my garage door would automatically open. Not very happy about that.

**Comment by REHolt** [comment]
One other config.json formatting question;  How do put comments in the file? I would like to make myself some notes and even put some additional entries in the config.json file for future use. I tried using the "#" character, and """,  but got an error when I started Fauxmo.

Again, probably a very basic question, sorry to  be wasting your time.

**Comment by n8henrie** [comment]
> Now, when I "Discover Devices" everything gets turned on.

Working on it: #31. The dev branch should not have this issue, but has a few more things I want to implement before merging into master and releasing to PyPI.

> One other config.json formatting question; How do put comments in the file?

No idea, might not be possible with JSON. Google it and let me know what you find.

**Comment by n8henrie** [comment]
Also please close this issue if you think it's been resolved (glad you figured it out).

**Comment by REHolt** [comment]
Thanks for the reply's. I will just have to keep an eye out for updates.

I did Google it and found several very old posts asking the same question. Seems that early versions of JSON supported comments but they took it out of later versions. There were several suggested work-around's, but even those no longer work. JASON files are strictly data files. Most of the posts were a couple of years old, so I was hoping they had put it back, seems to me even data files could use some comment information, but then I'm not really a programmer anyway.

Thanks, I will close this issue.

Robert Holt
