### ISSUE TITLE
Provide Host IP to Plugin

### ISSUE THREAD

**Issue by msp1974** [n8henrie/fauxmo#35]
Hi,

I am trying to work out a way to perform location awareness and have come up with the idea of creating a plugin for fauxmo that will allow virtual-virtual devices.

Basic plan is to have the ability to have multiple on_cmd for a device based on the IP of the host.  Such as
Echo 1: 10.0.0.1
Echo 2: 10.0.0.2

In config.json device config have 
"name":"Lights"
"on_cmd": {"10.0.0.1":"http://url/device1/on", "10.0.0.2":"http://url/device2/on"}

I have looked through the code and think I know how to do it but I am very new to Python and how to contribute to a github project.  As such, if you would be able to add the requesting host being passed to a plugin, such that I can hack around and build a plugin to do this that would be great.

If I get it working will be more than happy to contribute in your plugin repo.

Great tool btw - used this for some time and works really well on RPi3 Jessie linked to Domotiga via rest api

**Comment by n8henrie** [comment]
I guess I don't understand your use case, or what you mean by "virtual-virtual devices," or location awareness. Can you be more specific?

> In config.json device config have
"name":"Lights"
"on_cmd": {"10.0.0.1":"http://url/device1/on", "10.0.0.2":"http://url/device2/on"}

So do you want to say "turn the lights on" in one room and have something happen, but say "turn the lights on" in a different room and have something different happen?

I suppose it may be feasible if your echo has a static IP, but it sounds like a lot more work than just having two separate devices and saying "turn on the living room lights" and "turn on the kitchen lights," respectively. Maybe that's not what you meant though, let me know if I'm way off base.

**Comment by msp1974** [comment]
That is exactly what I'm trying to do.
Each room would have an echo and asking it to turn on the lights would turn the lights on in the room the echo is situated. I think this is simpler than having to know the name of each room, especially multiple bedrooms for guests.
Agreed on the static IP for the echo, unless fauxmo can pass the mac address or some other identifier that is fixed in the echo but not sure the protocol contains anything.  I am also looking at this to get over the 16 device limit per IP.  Instead on a device per room light, 1 single device with multiple endpoint in the config.
I have a bit more thinking as to how exactly the config will best work but would definitely need to have the echo ip passed to it (or whatever identifier)


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Nathan Henrie <notifications@github.com> Date: 15/11/2017  07:18  (GMT+00:00) To: n8henrie/fauxmo <fauxmo@noreply.github.com> Cc: Mark Parker <msparker@sky.com>, Author <author@noreply.github.com> Subject: Re: [n8henrie/fauxmo] Provide Host IP to Plugin (#35) 
I guess I don't understand your use case, or what you mean by "virtual-virtual devices," or location awareness. Can you be more specific?

In config.json device config have

"name":"Lights"

"on_cmd": {"10.0.0.1":"http://url/device1/on", "10.0.0.2":"http://url/device2/on"}

So do you want to say "turn the lights on" in one room and have something happen, but say "turn the lights on" in a different room and have something different happen?
I suppose it may be feasible if your echo has a static IP, but it sounds like a lot more work than just having two separate devices and saying "turn on the living room lights" and "turn on the kitchen lights," respectively. Maybe that's not what you meant though, let me know if I'm way off base.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/n8henrie/fauxmo","title":"n8henrie/fauxmo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/n8henrie/fauxmo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@n8henrie in #35: I guess I don't understand your use case, or what you mean by \"virtual-virtual devices,\" or location awareness. Can you be more specific?\r\n\r\n\u003e In config.json device config have\r\n\"name\":\"Lights\"\r\n\"on_cmd\": {\"10.0.0.1\":\"http://url/device1/on\", \"10.0.0.2\":\"http://url/device2/on\"}\r\n\r\nSo do you want to say \"turn the lights on\" in one room and have something happen, but say \"turn the lights on\" in a different room and have something different happen?\r\n\r\nI suppose it may be feasible if your echo has a static IP, but it sounds like a lot more work than just having two separate devices and saying \"turn on the living room lights\" and \"turn on the kitchen lights,\" respectively. Maybe that's not what you meant though, let me know if I'm way off base."}],"action":{"name":"View Issue","url":"https://github.com/n8henrie/fauxmo/issues/35#issuecomment-344506784"}}}

**Comment by n8henrie** [comment]
This will be a modest amount of work (to update all the existing plugins).

Because I don't have a use case for this feature and other projects require my time, I don't think I'll be able to implement it.

If you or anybody else wants to make a PR please feel free. I'll leave the issue open for 10 days or so to see if it stimulates any conversation or if you make any progress.

As a head start -- in `protocols.py`, I recommend using something like:

```python
peername = self.transport.get_extra_info('peername')
...
self.plugin.get_state(peername=peername)
...
self.plugin.on(peername=peername)
...
self.plugin.off(peername=peername)
```

https://docs.python.org/3/library/asyncio-protocol.html#asyncio.BaseTransport.get_extra_info

Would just need to update the ABC and all the plugins to accept peername as an extra kwarg, then make sure all the tests and linting passes.

**Comment by msp1974** [comment]
So I had fauxmo pass the host ip and created a plugin based on the restapi plugin that could detect which echo was making the request and switch different devices depending on that.

What I discovered, which I did not expect, is that the echo making the request is not necessarily the one you are talking to. It seems as though one of them has the role of controller and all requests come from this one. Switching off the controller echo does switch after a few seconds to another one to be the controller.

 Thought I would provide an update as it maybe useful info for anyone else wanting to try this. As such, you can not do location awareness using a wemo emulator.

**Comment by n8henrie** [comment]
That's one of the things I was afraid of -- thanks a ton for reporting back! Seeing that adding this functionality won't serve your use case, do you think it's appropriate to go ahead and close the issue?

**Comment by msp1974** [comment]
Yes.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Nathan Henrie <notifications@github.com> Date: 20/11/2017  00:08  (GMT+00:00) To: n8henrie/fauxmo <fauxmo@noreply.github.com> Cc: Mark Parker <msparker@sky.com>, Author <author@noreply.github.com> Subject: Re: [n8henrie/fauxmo] Provide Host IP to Plugin (#35) 
That's one of the things I was afraid of -- thanks a ton for reporting back! Seeing that adding this functionality won't serve your use case, do you think it's appropriate to go ahead and close the issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/n8henrie/fauxmo","title":"n8henrie/fauxmo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/n8henrie/fauxmo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@n8henrie in #35: That's one of the things I was afraid of -- thanks a ton for reporting back! Seeing that adding this functionality won't serve your use case, do you think it's appropriate to go ahead and close the issue?"}],"action":{"name":"View Issue","url":"https://github.com/n8henrie/fauxmo/issues/35#issuecomment-345562064"}}}

**Comment by n8henrie** [comment]
@msp1974 -- Take a look at your comment above, it seems to have contained an `api_key` that was in your email. I have redacted the api_key, but you might want to double check your sent emails and reset that key as it was publicly visible for a few hours.
