### ISSUE TITLE
python > 3.4 puts this out of reach for OSMC

### ISSUE THREAD

**Issue by owbear** [n8henrie/fauxmo#37]
- **Operating system and version**: OSMC, Debian Jessie based
- **Python version**: 3.4.2
- **Fauxmo version** (`fauxmo --version`): f4723ede7f7524e5e27b35fe68c48b067231d2a7

## My Issue

While I understand the urge to use the new typing module and other neatness in Python 3.6 this puts it out of reach for many RPi distributions. 

## [WHYT](http://mattgemmell.com/what-have-you-tried)

``sudo apt install python36``

**Comment by n8henrie** [comment]
I used Fauxmo with 3.6 when I was on Jessie, it's not that difficult to install a more modern version of Python (3.5 was released [over 2 years ago](https://www.python.org/downloads/release/python-350/)). FYI HomeAssistant, the biggest and most successful Python-based home automation software, is [also dropping 3.4 support](https://home-assistant.io/blog/2017/10/06/deprecating-python-3.4-support/), soon.

I dislike the `asyncio.coroutine` and `yield from` syntax required by 3.4, replaced by the much cleaner `async def` and `await` syntax in 3.5 (which is now in Stretch). The type hints, f-strings, and speed optimizations in 3.6 are fantastic, I have no interest in going back.

I recommend you look into [pyenv](https://github.com/pyenv/pyenv), which I use on all of my devices (including my Pis, works great) to ensure I can easily install, run, and switch between whichever versions of Python I want. They have easy-to-follow installation instructions, I bet you can get it up and running in no time.

**Comment by owbear** [comment]
Thanks @n8henrie I need to buy another RPi rather than trying to fit everything in the same box :-) 👍
