### ISSUE TITLE
Alexa-Discover turns on most of my FauxMo nodes

### ISSUE THREAD

**Issue by SteveRMann** [n8henrie/fauxmo#39]
Not sure it's a bug, but..
When I do a Discover on Alexa or in the Aelexa app, many, not all, of the esp8266-01 nodes running FauxMo get turned on.  Any ideas?

**Comment by n8henrie** [comment]
They are running FauxmoESP, not Fauxmo (i.e. via micropython), right? If so, please close this issue and open one at FauxmoESP, very different projects.

**Comment by SteveRMann** [comment]
I get the two mixed up, but yes, I am using fauxmoESP.h from 'github.com/ItKindaWorks'.
I recall that you said that fauxmo doesn't do this, so I will try migrating them to that library.

**Comment by n8henrie** [comment]
Sounds good, you'll need to open an issue in that repo in that case.
