### ISSUE TITLE
Discovery stopped working

### ISSUE THREAD

**Issue by Astroman** [n8henrie/fauxmo#4]
The discovery process seems to have stopped working. At first I noticed this with an Hue emulation plugin I use with Indigo and this was confirmed to be broken, probably due to a recent Echo update that added thermostat control. Then I went back to FauxMo and could not get discovery working with it either. 

I'm not sure about FauxMo, since I had deleted my discovered devices, but with the other software already discovered devices continued to work. So I suggest not forgetting other devices while anyone checks this out. I also wonder whether discovery works with real Hue or WeMo devices.

**Comment by n8henrie** [comment]
I can't replicate. I removed a device and was able to re-add as usual, and it continues to function as before.

**Comment by Astroman** [comment]
Hmmm. OK, I’ll try harder to get my fauxmo installation working again. It seems to start up but does not respond to Echo discoveries. Are you on the latest 3077 Echo firmware?

**Comment by Astroman** [comment]
I turned on the extra debug mode with -vv and FauxMo seems to be responding with device data as it's always done so I think my FauxMo installation is OK. However, Alexa is not accepting the data as discovered devices. This is the same symptom as my other emulated interfaces. Others are seeing the same issue and the Indigo developer attributes it to changes in the Echo firmware but does not plan to work on it for a while due to other priorities. If it is working for you with the latest Echo firmware, this could be an important clue.

**Comment by n8henrie** [comment]
Yes, I'm on 3077. It did take a few tries (it always has for me) but like I said it was able to add devices and continues to work.

**Comment by Astroman** [comment]
Understood, thanks. I haven’t been able to get it to work at all. I’ll let you know if I find out anything else.

**Comment by n8henrie** [comment]
I've just verified again -- removed all device and have been able to re-add. Did take a few tries and a few minutes, but was able to get them re-added without any changes to configuration or anything.

**Comment by Astroman** [comment]
Very strange. Can you think of anything I should try or look at in the debug log to find out why Alexa isn’t seeing my devices?

**Comment by n8henrie** [comment]
>  However, Alexa is not accepting the data as discovered devices.

What do you mean by this? Is there some kind of error code, or is it just not working?

In the extra debug logs, are you seeing `DEBUG    Responding to setup request with:`  for each of your devices?

**Comment by Astroman** [comment]
Sorry, I meant that Alexa discovers no devices even though the debug log seems to show FauxMo responding to the discovery process.

The debug logs show something like the following for each of my devices (x'ing out the uuid socket number):

<?xml version="1.0"?>
<root>
<device>
<deviceType>urn:Fauxmo:device:controllee:1</deviceType>
<friendlyName>family room light</friendlyName>
<manufacturer>Belkin International Inc.</manufacturer>
<modelName>Emulated Socket</modelName>
<modelNumber>3.1415</modelNumber>
<UDN>uuid:Socket-1_0-xxx</UDN>
</device>
</root>
2016-03-14 19:08:09 fauxmo       DEBUG    setup.xml requested by Echo
2016-03-14 19:08:09 fauxmo       DEBUG    Responding to setup request with:
HTTP/1.1 200 OK
CONTENT-LENGTH: 342
CONTENT-TYPE: text/xml
DATE: Tue, 15 Mar 2016 02:08:09 GMT
LAST-MODIFIED: Sat, 01 Jan 2000 00:01:15 GMT
SERVER: Unspecified, UPnP/1.0, Unspecified
X-User-Agent: Fauxmo
CONNECTION: close

**Comment by n8henrie** [comment]
FYI UUID is supposed to be constant for a given device, so it's generated in a predictable way from the device name. If you're going to take the precaution of xxing out the UUID, you should also provide fake device names.

That response looks identical to mine -- I'm not sure it's a Fauxmo problem. Have you tried rebooting the Echo? Did you say you're running Fauxmo on a Mac Mini?

**Comment by Astroman** [comment]
Yes, on a Mac Mini. I don’t think it’s a FauxMo problem either since the Alexa-Hue Indigo plugin is having the same problem. I was just hoping that the debug log in FauxMo might provide some clue as to why Alexa is not seeing the devices. And I have tried rebooting the Echo and will try again.

**Comment by Astroman** [comment]
I pleased, albeit surprised to report that Alexa is discovering devices again, both in FauxMo and the Indigo Hue plugin. Others on the Indigo forum are reporting the same thing although some never seemed to have the problem. I have no idea why and there is no change in the Alexa firmware version. Will probably remain a mystery with a happy ending. In any event, thanks for you help!

—Dave

**Comment by n8henrie** [comment]
Weird. Well, glad to hear it's back to working!
