### ISSUE TITLE
Should Fauxmo switch to emulating a Hue?

### ISSUE THREAD

**Issue by n8henrie** [n8henrie/fauxmo#41]
As many users have noted, something has changed in the way WeMo devices interact with the newer Echos, which [breaks Fauxmo for these devices](https://github.com/n8henrie/fauxmo/issues/38).

While we're slowly trying to figure out a workaround, one possibility would be to move from emulating a WeMo device to emulating a Hue. This is the route that HomeAssistant has taken from the beginning, and it seems to work well:

- https://home-assistant.io/components/emulated_hue/
- https://github.com/home-assistant/home-assistant/tree/dev/tests/components/emulated_hue

I'm not sure how much work it would be, but this may be one way to work around this new limitation.

If I go this route, I will also likely rename the library, making a break from the original work by makermusings, since it is already a near complete re-write and at that point will no longer have anything to do with WeMo. I'd like the new name to be something more descriptive -- I don't have anything in mind, but would be open to suggestions.

**Comment by Perforex** [comment]
Good idea to at least investigate the use of Hue. Some name suggestions:
substithuet
replichue
huemime

**Comment by pauly** [comment]
Guesshue

Just got an echo plus and excited by the possibilities of this project

**Comment by n8henrie** [comment]
I think we have at least temporized the issue with the latest changes to dev branch, closing for now but may reopen at some point.

Thanks for your suggestions.
