### ISSUE TITLE
Wemo Remote Access / Different Wifi Network

### ISSUE THREAD

**Issue by jmschonfeld** [n8henrie/fauxmo#48]
- **Operating system and version**: Raspbian Jessie (8.0)
- **Python version**: 3.6.0
- **Fauxmo version** (`fauxmo --version`): 0.4.5
- **Echo device type** (e.g. Echo, Echo Plus, Dot):  Dot
- **[Echo Firmware Version](https://github.com/n8henrie/fauxmo/blob/dev/README.md#troubleshooting--faq)**: 597465220

## My Issue
Does fauxmo support the ability to connect via remote access (for example, connect my device to my online wemo account)? For my current internet/wifi setup (a college dorm room) my raspberry pi and echo dot must be on separate wifi networks, so it is not detecting my raspberry pi. I would like to workaround this issue by connecting the raspberry pi to my online wemo account, and then connecting the echo dot to wemo via the wemo skill. Is this possible, or are there any other options to connect the Alexa to a device at a specific IP address?

## [WHYT](http://mattgemmell.com/what-have-you-tried)

Following all given instructions and searching for the raspberry pi device

---

Please make sure you've taken these steps before submitting a new issue:

- [x] Try to reproduce the issue with Fauxmo installed in a
  [venv](https://docs.python.org/3/library/venv.html)
- [x] Ensure you're running a supported version of Python
    - Requires Python >= 3.2 for Fauxmo < 0.3.0
    - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
    - Requires Python >= 3.6.0 for Fauxmo >= 0.4.0
- [ ] Run Fauxmo in debug mode (`-vvv`) and include relevant output
- [ ] Include your Fauxmo `config.json`
- [x] Search the existing (including closed) issues
- [x] Please use [codeblocks][1] around your debug output and config

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by n8henrie** [comment]
I don't think this will be possible, or if it is possible I'm not sure how
to accomplish it.

If you look at the `protocol_notes.md` document, the Echo reaches out and
contacts Fauxmo through a multicast broadcast that will only travel over a
local network (as far as I know, no expert here). So there is nothing I can
change about that -- the Echo is what coordinates initially contacting the
device and letting the devices "know about each other."

The only workaround that comes to mind would be making your RPi into a WiFi
access point -- if you could use ethernet in to provide access then use a
WiFi adapter to *broadcast* a network from the Pi, you could probably
connect the Echo to that network and then they'd be able to communicate.
Not sure.

If you end up giving that a shot, let me know how it works.

**Comment by jmschonfeld** [comment]
Unfortunately it seems that you are right and it is not possible to do the way I am hoping to do it. Instead I found the software called Home Assistant which seems to accomplish my goal but in a different manner. Thank you for the suggestions!

**Comment by n8henrie** [comment]
HomeAssistant is an awesome project, can definitely do everything Fauxmo
does (plus much, much, much more).
