### ISSUE TITLE
All is well except On turns the relay off and Off turns the relay on.

### ISSUE THREAD

**Issue by HPD611** [n8henrie/fauxmo#51]
Windows 10
D1 Mini ESP8266 ESP-12F N Compatible NodeMcu Arduino
Fauxmo ESP v. 2.4.2
Echo Dot
Echo Firmware Version: Client: 1.24.4244.0 Bridge: 2.2.2043.0

(https://github.com/n8henrie/fauxmo/blob/dev/README.md#troubleshooting--faq)**: 

Sorry to bother you, and I will begin with apologizing for my lack of experience with Arduino coding. I understand the basics and can usually work my way through problems, but this one has me stumped. Thank you in advance for any help you can give me.

I've attached my sketch I've gotten everything to work with the exception of the fact that when I ask it to turn my relay on, it turns it off, and when I ask it to turn the relay off, it turns it on. I'm using a solid state relay, and I also tried it with a mechanical relay. It just seems to send the signal when it's gotten the off instruction and cuts the signal when it's received the on instruction.

Please let me know if you have any ideas and thanks so much for your time and all of your hard work. I'm very excited to see what all we can put together with these boards!

[fauxmoESP_Basic_D1_AlexaV2.ino.ino.zip](https://github.com/n8henrie/fauxmo/files/1715194/fauxmoESP_Basic_D1_AlexaV2.ino.ino.zip)

**Comment by n8henrie** [comment]
Wrong project, I think you're looking for: https://bitbucket.org/xoseperez/fauxmoesp
