### ISSUE TITLE
commandline plugin usage exist?

### ISSUE THREAD

**Issue by drduker** [n8henrie/fauxmo#53]
- **Operating system and version**:Rasbian 8 (Jessie)
- **Python version**:3.6.1
- **Fauxmo version** (`fauxmo --version`):0.4.5
- **Echo device type** (e.g. Echo, Echo Plus, Dot):  Echo and Echo Dot
- **[Echo Firmware Version] - Not related
(https://github.com/n8henrie/fauxmo/blob/dev/README.md#troubleshooting--faq)**: 

## My Issue
When I install fauxmo 0.4.5 it no longer comes with the commandlineplugin.py.  Is this still supported?  And if so does it support the state command?  Can I use it along side fo the simplehttp plugin in my json?

My use case is turning off and on GPIO pins on the raspberry pi and checking the state (state seems to be a new feature with the http plugin).

`{
  "FAUXMO": {
    "ip_address": "auto"
  },
  "PLUGINS": {
    "CommandLinePlugin": {
      "path": "/opt/pyenv/versions/3.6.1/lib/python3.6/site-packages/fauxmo/plugins/commandlineplugin.py",
      "DEVICES": [
        {
            "name": "Lounge lights",
            "port": 42131,
            "on_cmd": "touch testfile.txt",
            "off_cmd": "rm testfile.txt",
            "state_cmd": "ls testfile.txt"
        }
      ]
    },
    "SimpleHTTPPlugin": {
            "DEVICES": [
                {
                    "port": 12340,
                    "on_cmd": "http://192.168.1.127/myserver/fakeswitches/01/on",
                    "off_cmd": "http://192.168.1.127/myserver/fakeswitches/01/off",
                    "method": "GET",
                    "name": "fake switch one"
                },
                {
                    "port": 12341,
                    "on_cmd": "http://localhost:54321/devices/garage%20light",
                    "off_cmd": "http://localhost:54321/devices/garage%20light",
                    "on_data": {"isOn": 1},
                    "off_data": {"isOn": 0},
                    "user": "this",
                    "password": "that",
                    "method": "PUT",
                    "name": "fake Indigo switch"
                },
                {
                    "name": "fake home assistant switch by REST API",
                    "port": 12342,
                    "on_cmd": "http://192.168.1.127:8123/api/services/switch/turn_on",
                    "off_cmd": "http://192.168.1.127:8123/api/services/switch/turn_off",
                    "method": "POST",
                    "headers": {"x-ha-access": "your_hass_password"},
                    "on_data": {"entity_id": "switch.fake_hass_switch"},
                    "off_data": {"entity_id": "switch.fake_hass_switch"}
                }
            ]
        }
  }
}
`

Error:
ModuleNotFoundError: No module named 'fauxmo.plugins.commandlineplugin'
...
FileNotFoundError: [Errno 2] No such file or directory: '/opt/pyenv/versions/3.6.1/lib/python3.6/site-packages/fauxmo/plugins/commandlineplugin.py'...

## [WHYT](http://mattgemmell.com/what-have-you-tried)

---

Please make sure you've taken these steps before submitting a new issue:

- [ ] Try to reproduce the issue with Fauxmo installed in a
  [venv](https://docs.python.org/3/library/venv.html)
- [ ] Ensure you're running a supported version of Python
    - Requires Python >= 3.2 for Fauxmo < 0.3.0
    - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
    - Requires Python >= 3.6.0 for Fauxmo >= 0.4.0
- [ ] Run Fauxmo in debug mode (`-vvv`) and include relevant output
- [ ] Include your Fauxmo `config.json`
- [ ] Search the existing (including closed) issues
- [ ] Please use [codeblocks][1] around your debug output and config

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by n8henrie** [comment]
> it no longer comes with the commandlineplugin.py

This repo has never had commandlineplugin. You're looking for: https://github.com/n8henrie/fauxmo-plugins/

**Comment by TimothyBramlett** [comment]
I was confused also bc of this in the README

![image](https://user-images.githubusercontent.com/7890441/38763533-7de3112e-3f63-11e8-9f75-be3891ff4691.png)

**Comment by n8henrie** [comment]
Good catch, thank you.

**Comment by sikalabsga** [comment]
I'm experiencing the same module not found error. In my working directory, I have created a user plugin following n8henrie's example and also followed with the naming convention, called switcherplugin.py . In the same folder a created a venv and activated it and then installed fauxmo. However, when I run fauxmo -c config.json [-v] I get the error that my custom python plugin is not found. 'fauxmo.plugins.switcherplugin'.
config.json
{
    "FAUXMO": {
        "ip_address": "auto"
    },
    "PLUGINS": {
        "SwitcherPlugin": {
            
            "path": "~/MyHomeAutomationServer/switcherplugin.py",
            "DEVICES": [
                {
                                "port": 12340,
                                "name": "garage"
                            },
                            {
                                 "port": 12341,
                                 "name": "coffee-marker"
                            }
            ]
        },
        "SimpleHTTPPlugin": {
            "DEVICES": [ 
                {
                    "port": 12340, "on_cmd": "http://192.168.1.127/myserver/fakeswitches/01/on", "off_cmd": "http://192.168.1.127/myserver/fakeswitches/01/off", "method": "GET", "name": "fake switch one" 
                            }, 
                            { 
                                "port": 12341, "on_cmd": "http://localhost:54321/devices/garage%20light", "off_cmd": "http://localhost:54321/devices/garage%20light", "on_data": {"isOn": 1}, "off_data": {"isOn": 0}, "user": "this", "password": "that", "method": "PUT", "name": "fake Indigo switch" 
                                                        
                            }, 
                                                        
                            {
                                "name": "fake home assistant switch by REST API", "port": 12342, "on_cmd": "http://192.168.1.127:8123/api/services/switch/turn_on", "off_cmd": "http://192.168.1.127:8123/api/services/switch/turn_off", "method": "POST", "headers": {"x-ha-access": "your_hass_password"}, "on_data": {"entity_id": "switch.fake_hass_switch"}, "off_data": {"entity_id": "switch.fake_hass_switch"} 
                                                        
                            } 
                                                       
            ]
                    } 
        
    }
}

userplugin: switcherplugin.py


from fauxmo.plugins import FauxmoPlugin


class SwitcherPlugin(FauxmoPlugin):
    """
        Publishes the on/off state requested,
        and the IP address of the Echo making the request.
    """
    
    def __init__(self, name: str, port: int) -> None:
        super().__init__(name=name, port=port)
        
    def on(self):
        """Turn the named device on.
        Returns: Whether the device seems to have been turned on.
        """
        pass
        

    def off(self):
        """Turn the named device off.
        Returns: Whether the device seems to have been turned off.
        """
        pass
        

    def get_state(self):
        """Query the state of the Home Assistant device.
        Returns: Device state as reported by HomeAssistant
        """
        pass

**Comment by n8henrie** [comment]
@sikalabsga -- please create a new issue.
