### ISSUE TITLE
POST method doesn't support raw on/off data

### ISSUE THREAD

**Issue by hestela** [n8henrie/fauxmo#54]
- **Operating system and version**: NixOS 17.09.3129.1dcd022f01b (Hummingbird)
- **Python version**: 3.6
- **Fauxmo version** (`fauxmo --version`): v0.4.6
- **Echo device type** (e.g. Echo, Echo Plus, Dot):  Echo Dot
- **[Echo Firmware Version](https://github.com/n8henrie/fauxmo/blob/dev/README.md#troubleshooting--faq)**:  601481020

## My Issue
To send commands to openhab items I need to be able to send raw data using POST.
I basically need to replicate a command like this:
` curl -X POST --header "Content-Type: text/plain" --header "Accept: application/json" -d "OFF" "http://127.0.0.1:7080/rest/items/Lights"`

on_data and off_data are required to be dict objects. And it seems that in [simplehttpplugin.py#L126](https://github.com/n8henrie/fauxmo/blob/master/src/fauxmo/plugins/simplehttpplugin.py#L126), urlencode forces a '=' into the POST data.
simple example:
```python
>>> import urllib
>>> dict = {'' : 'ON'}
>>> urllib.urlencode(dict)
'=ON'
```
Which causes this error in the openhab logs:
`2018-04-17 17:30:08.578 [WARN ] [thome.io.rest.core.item.ItemResource] - Received HTTP POST request at 'items/Lights' with an invalid status value '=ON'.`

I couldn't figure out the right way to force raw text to be sent with the POST command. It seems this is the only want to set the state of items using the openhab REST API.

config.json:
```json
{
    "FAUXMO": {
        "ip_address": "auto"
    },
    "PLUGINS": {
      "SimpleHTTPPlugin": {
        "DEVICES": [
          {
            "port": 52002,
            "on_cmd":  "http://127.0.0.1:7080/rest/items/Lights",
            "off_cmd": "http://127.0.0.1:7080/rest/items/Lights",
            "method": "POST",
            "headers": {"Content-type": "text/plain", "Accept": "application/json"},
            "name": "All Lights",
            "on_data": {"": "ON"}
          }
        ]
      }
    }
}
```

FWIW, I was able to make this work in a much older version (v0.3.2), where i was able to put just a string into on_data. 

[nix expression](https://github.com/hestela/dot_files/blob/master/nix/pkgs/fauxmo.nix)

**Comment by n8henrie** [comment]
Also, can you point me to relevant docs for this openhab functionality you're looking to leverage?

**Comment by hestela** [comment]
short summary of the rest api [here](https://docs.openhab.org/configuration/restdocs.html)
[demo website](http://demo.openhab.org:8080/doc/index.html)

If you check out the demo website, you can expand 'Items' and then expand the POST section.
demo website is interactive and lets to try things out, and using the first GET in the items tab gives you a list of all the items.

Items are the main way to turn stuff off, on, dim lights, etc in openhab. Not sure why the chose the names things and items for different functions, really confusing :\

Also, thanks for great project! Using my hue lights with fauxmo seems to be somewhat more stable than using the hue lights with the hue integration w/alexa

**Comment by n8henrie** [comment]
Please test the dev branch and let me know.

**Comment by hestela** [comment]
I tried out the dev branch and  "on_data": "ON" and off were working!

but I ran into a problem with the NixOS builder: (nixos-rebuild build)
```
building
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 5, in <module>
    readme = readme_file.read()
  File "/nix/store/ljhgdba6n8ag6f8clpi4m9zizm7b8mx3-python3-3.6.5/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcb in position 2080: ordinal not in range(128)
```

I found one other nixos package that had the same issue https://github.com/NixOS/nixpkgs/issues/35659

they just made a PR to make the setup.py accept utf-8. https://github.com/pytest-dev/pytest-mock/pull/107/files
they changed the long_description to be:
```python
long_description=open('README.rst', encoding='utf-8').read(),
```

I'll open a PR about long_description.

**Comment by n8henrie** [comment]
Sweet, and thanks for the PR
