### ISSUE TITLE
Add close and lookup functionality to plugins

### ISSUE THREAD

**Issue by howdypierce** [n8henrie/fauxmo#58]
## My Issue
I'd like to propose two additions to the plugin API.  I've got both of these implemented already and I'm happy to submit a PR.

1) Add a close function.  I've got a plugin which runs on a Raspberry Pi and uses RPi.GPIO to truly implement a Wemo switch ... meaning, the Pi controls a relay which switches an electrical outlet. The problem is, when you stop the fauxmo service, there is no opportunity for the plugin code to shut down the GPIO state cleanly.  More generically, I would think many plugins might need to clean up before exiting.

   I'd propose that src/fauxmo/fauxmo.py keeps track of the plugin instances it creates, and then at shutdown it runs through those instances and calls a new close function on each.  For backward compatibility, I've added a do-nothing (but non abstract) FauxmoPlugin.close() function.  If plugins don’t need this functionality they can ignore the whole issue, but those plugins that need to perform cleanup can override close().  Existing plugins do not need to be modified.

2) Add a lookup function.  This might be a little more of a stretch, but in some cases it might be useful for multiple plugin instances to interact with each other.  An example which I have implemented is a "schedule" plugin.  This schedule plugin in turn controls another plugin.  So, for instance, I have my GPIO plugin named "Kitchen Light".  You can use Alexa to "turn on kitchen light".  Then I have a second plugin, the schedule plugin, which is set to turn the kitchen light on at 5 am and turn it off at sunrise.  Because this schedule plugin is itself a fauxmo instance, you can also use Alexa to "turn on kitchen light schedule".  

   However, in order for this whole approach to work, the schedule plugin instance needs to be able to find the GPIO plugin instance at runtime.

   Extending the idea from the close function above, we're already maintaining a record of created plugin instances in fauxmo.py.  So I added a lookup function which allows plugins to find each other by name.  Therefore in the schedule plugin case, one of the parameters in config.json is the name of the "slaved" plugin, and when it comes time for the schedule to turn on the lights, it can do so.

As I mentioned, I've got both the above implemented.  Look forward to your thoughts.

**Comment by howdypierce** [comment]
One thing I should have pointed out originally: Adding the lookup function necessarily means that no two plugin instances can have the same name. It seems to me this should be a restriction anyway -- I wouldn’t think Alexa would work as expected with two wemos named the same thing on the network.  However, at least the test_config.json file violates this assumption, with two "fake Indigo switch" devices. (So to get the tests to pass I had to edit the test config.)

**Comment by n8henrie** [comment]
Great thoughts.

\# 1: I've been thinking about the close issue much of the day -- totally makes sense. I agree, should be implemented as a non-abstract method to avoid a breaking API change for existing users. Instead of a `.close()` method, I really think this seems like a great place for a context manager, if that's possible with the asyncio API. Will look into it. Would definitely want to see what you've been using.

\# 2: I'm more hesitant about this one, ensuring interoperability between plugins seems easy to make the codebase significantly more complicated going forward. For most users, using the Routines built into Alexa seems like a cleaner solution for scheduling something, no? Do you have another example use case handy? Would be interested to take a look at the code you're using for this, but would want to think about it before moving forward.

**Comment by howdypierce** [comment]
1) I pushed my changes up to my github [fork](https://github.com/howdypierce/fauxmo/tree/plugin-close), if you want to take a look.  It's about 13 lines diff.  Happy to submit this as a PR if you like.

2) I understand your complexity concern. To address the question about Alexa Routines -- their scheduling exists but it's relatively primitive.  For instance, it doesn’t support sunrise/sunset or randomization, and it can't be turned off without completely deleting the Routine.  (Whereas what I'm trying to implement would allow you to have a schedule that you "turn on" when you leave for vacation, for instance.)  More generically, in the case where one host has multiple fauxmo instances running, it seems that it would not be that uncommon for state changes in one instance to drive state changes in another.  But I don’t have any (uncontrived) examples other than the schedule.

3) You will also see in that fork a one-line addition to utils.py:module_from_file().  When loading a plugin, I add the plugin's directory to sys.path. This allows plugins to import other python modules that sit beside them in the directory tree, which is convenient.

**Comment by n8henrie** [comment]
\# 1. Why don't you go ahead and submit a PR -- you deserve credit for the idea and initial work!

I've experimented a bit, and I think I'd like to implement it as a `.fauxmoplugin` attribute to `server`. That way I don't need additional list to keep track or, or have to loop over an additional list at close time, just call `server.fauxmoplugin.close()` right after the debug "shutting down server 1" log.

It looks like [loop.shutdown_asyncgens](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.shutdown_asyncgens) might be a more official way to do this via an [`aclose`](https://docs.python.org/3/reference/expressions.html#agen.aclose) coroutine, but I don't know enough about asyncio to implement it well.

\# 2. I agree this is an interesting idea, but I'm going to wait on it for now. Honestly it's the kind of thing that HomeAssistant *excels* at, and if you haven't looked there, I would really recommend it.

\# 3. Because this is a convenience feature that may have security ramifications, I think I'll leave it out. I want the import path to be very explicit to help avoid running malicious or accidental code. Users that want to implement the feature independently can easily do so by putting your `sys.path` trick into their plugin code (i.e. something like `sys.path.append(str(pathlib.Path(__file__).parents[0]))`); empowering the user in this way was one of the main reasons for the plugin architecture.

An example scenario:

```shellsession
$ cat foo.py
import logging

logger = logging.getLogger()

logger.warning("Friendly logging here")
$ python3 foo.py
Friendly logging here
$ cat <<'EOF' > logging.py
> class DangerousClass:
>     def warning(self, message):
>         print("Fooled you!")
>
> def getLogger():
>     return DangerousClass()
> EOF
$ python3 foo.py
Fooled you!
```

**Comment by howdypierce** [comment]
Thanks for your comments.  PR submitted for 1.

For 3, I don’t agree that your sample is equivalent to what I had proposed.  The sample code shows a huge security hole because in sys.path, Python has put your current directory AHEAD of wherever the logging module is found. My proposal appended the plugin's directory to the search path, so would not have opened that particular hole.  And in any event, adding lines at the top of each plugin file to modify sys.path, as suggested, has the whatever same vulnerabilities might be, just less elegant; it takes four lines of code including one with a `# noqa` to reach the same end.)

But no sweat, appreciate you responding to all this.

**Comment by n8henrie** [comment]
> The sample code shows a huge security hole because in sys.path, Python has put your current directory AHEAD of wherever the logging module is found. My proposal appended the plugin's directory to the search path, so would not have opened that particular hole.

You're entirely correct. Reading a little more on it, it seems that appending to the path is a pretty well established ([and officially recommended](https://docs.python.org/3.6/install/index.html#modifying-python-s-search-path)) way to accomplish this:

> The most convenient way is to add a path configuration file to a directory that’s already on Python’s path, usually to the .../site-packages/ directory. Path configuration files have an extension of .pth, and each line must contain a single path that will be appended to sys.path. (Because the new paths are appended to sys.path, modules in the added directories will not override standard modules. This means you can’t use this mechanism for installing fixed versions of standard modules.)

I guess my lack of expertise, which leads to such embarrassing oversights, is part of the reason I hesitate to pull in features like this -- it's hard for me to feel confident that it's not putting users at risk.

> And in any event, adding lines at the top of each plugin file to modify sys.path, as suggested, has the whatever same vulnerabilities might be, just less elegant. It takes four lines of code including one with a # noqa to reach the same end.

True, but if there were indeed vulnerabilities, if I insert those 4 lines of code for all users of Fauxmo vs if a user takes it upon themselves to insert those 4 lines, it makes a great deal of difference... to me at least. I'm just trying to be cautious.

At first, I also envisioned very limited benefit -- this seems like something that few users will take advantage of; I expect most users to install dependencies into the same virtualenv that runs Fauxmo (this is what I do). Alternatively, I'm sure one could add a `.pth` file or manipulate the `PYTHONPATH`, or just add the 4 lines into their plugin as per above.

However, I was thinking about it today, and I realized that this change might allow users to install plugin dependencies separately from their Fauxmo instance, using pip's `--target`. I just tried it out, and it seems to work. In the same directory as `fooplugin.py`, run `pip install -t . anotherlib`, which installs that library alongside, and after the `sys.path` tweak, is importable by `fooplugin.py`.

I can imagine this being much more helpful in this case.

I also imagine it could lead to some issues with conflicting dependencies, except that Fauxmo doesn't have any.

Is this more along the lines of what you'd been using it for?

**Comment by howdypierce** [comment]
Sorry for the delayed response.

To be honest, I wasn’t thinking that hard about this when I proposed it, so it's always good to have one's assumptions challenged.

During development, I had my plugins in a separate directory, and the project got to the point where I wanted to split some code into multiple files--in my case this was a subclass/superclass relationship but there are all sorts of reasons you'd want to do this. I had not yet made my plugins pip installable. (In fact, I still haven’t, though it's on the to-do list.)

I don't think there's a huge security hole created by appending to the sys.path, especially since elsewhere in your documentation you tell them to run Fauxmo as an unprivileged user. And we could document this issue in the docs about config.json--something to the effect of "Be aware, any directory that contains fauxmo plugins will be appended to the Python system path while Python is running, so any other Python modules in this directory might be loaded by unscrupulous plugins."

One thing I'd think about would be, what is the expectation for plugin developers in terms of how Pythonic you are expecting them to be? When I've worked on commercial software projects with APIs, we've often held ourselves to a high standard but also tried to make the bar considerably lower for our development community. So my personal bias would be to make it easy for people to pick up Fauxmo and create out a plugin with very low plugin-developer overhead--and as a result, I'd try to set Fauxmo up to work generally as they expect. "Overhead" in this case would be requiring plugin devs to package their plugins as pip-installable, or for that matter requiring them add code to find their other files.

However, while this "make it super easy" might be the goal for some projects, it might not be a goal for Fauxmo, and that's ok. Also of course reasonable minds can disagree about how hard it is to create a setup.py file, because clearly that's not too hard either.

**Comment by n8henrie** [comment]
Also sorry for delayed response on my end.

Thanks so much for your input and reasonable communication. As a hobbyist,
I can't tell you how cool it is to be getting constructive and well-meaning
input from a real developer on one of my projects.

After learning a bit more on the topic and after this discussion, I've
changed my mind and think this would be worth incorporating. Would you mind
putting in a PR?

**Comment by howdypierce** [comment]
PR submitted.  

Happy to help, although looking around at my team I’m not certain that much (any?) deference is due to a "real developer" :)
