### ISSUE TITLE
This fauxmo fork on ESP ?

### ISSUE THREAD

**Issue by MopheusDG** [n8henrie/fauxmo#59]
Hi, I've been using FauxmoESP for some time and it started having some serious problems with Gen1/2 of Echo's, now 80% of the time I get an "Switch X is not responding" error, while that doesn't happen if I send the SOAP messsage from my cellphone... so it's something related to Alexa's Wemo's message probably.... so my question is, is this fauxmo version working fine with Alexa lately ?

And any change to get an ESP version of this beautiful code ? ;)

**Comment by n8henrie** [comment]
Thanks for the kind words!

Yes, mine is working for me.

No, unfortunately I don't plan on an ESP fork -- I don't know enough C++,
and I'm not sure if it would work on MicroPython (an interesting thought
though).

**Comment by MopheusDG** [comment]
May I can try to update the FauxmoESP code myself... did you notice/recall any change on the Alexa - Fauxmo messages the last months that could help me identify the problem ?

**Comment by n8henrie** [comment]
Does the switch seem to work and you just get the error? Or do you get the error and the switch doesn't work, either?

If the former, you may need to write a method for the newish getbinarystate request.

**Comment by MopheusDG** [comment]
With FauxmoESP it works sometimes (Alexa says OK and the switch changes it's state), and sometimes Alexa says the X switch is not responding and the switch does not change the state. I'm not sure what Alexa is sending or receiving so not sure why it fails sometimes... I'm not even sure how to monitor those packages to find a possible problem.

**Comment by n8henrie** [comment]
Honestly that sounds more like an issue with your network / hardware / internet connection.

I don't think I can be of much help to you, I recommend you ask the FauxmoESP community.
