### ISSUE TITLE
Change command word?

### ISSUE THREAD

**Issue by ssmmoo1** [n8henrie/fauxmo#66]
- **Operating system and version**:
- **Python version**:
- **Fauxmo version** (`fauxmo --version`):
- **Echo device type** (e.g. Echo, Echo Plus, Dot): 
- **[Echo Firmware Version](https://github.com/n8henrie/fauxmo/blob/dev/README.md#troubleshooting--faq)**: 

## My Issue

Not really an issue just a question I can't find the answer to. Is there a way to change the command from "alexa turn on ..." to "alexa open ..."   

## [WHYT](http://mattgemmell.com/what-have-you-tried)

---

Please make sure you've taken these steps before submitting a new issue:

- [ ] Try to reproduce the issue with Fauxmo installed in a
  [venv](https://docs.python.org/3/library/venv.html)
- [ ] Ensure you're running a supported version of Python
    - Requires Python >= 3.2 for Fauxmo < 0.3.0
    - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
    - Requires Python >= 3.6.0 for Fauxmo >= 0.4.0
- [ ] Run Fauxmo in debug mode (`-vvv`) and include relevant output
- [ ] Include your Fauxmo `config.json`
- [ ] Search the existing (including closed) issues
- [ ] Please use [codeblocks][1] around your debug output and config

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by mancuniancol** [comment]
Just use a routine and you can customize the call

**Comment by n8henrie** [comment]
@mancuniancol has a reasonable suggestion -- you can make your own trigger names with a routine.

Currently Fauxmo only supports presenting devices as a "switch," which means you get on and off (but don't have to use some subphrase like "alexa, tell fauxmo to..."). If there are Belkin Wemo devices that Alexa can interact with using whatever phrase you're interested in then I think the functionality is possible in Fauxmo, but I don't know if this is possible, and it's not currently implemented even if possible.
