### ISSUE TITLE
fauxmo with different echo dots

### ISSUE THREAD

**Issue by Schwenkner** [n8henrie/fauxmo#68]
First let me explain my configuration.

I'm running a C# implementation adopted of your fauxmo on several Raspies with Windows 10 IoT Core. The fauxmo implementation I did by my own, since I couldn't find a solution for UWP. It allows me to define several devices on my Raspi. If the command is invoked, the Raspi can handle different actions according the given device, i.e., sending an HTTP request to switch something. The two Raspies (with almost the same program running) are located at different places in different networks (two houses in different cities).

Till yesterday I had an echo dot 2 and all worked well. On one Raspi I've had a fauxmo device named "heating". This device was able to send an HTTP request to the second Raspi, which then will turn the heating on or off.

Now I bought an echo dot 3, established it on the network in the other house, added a device also named "heating" to that Raspi. First fauxmo couldn't find the device. I've searched a bit in the internet and found, that newer versions do not serach with "urn:Belkin:device:**", but with "upnp:rootdevice". Since this was easy to modify, I enabled this for my program and viola, the device "heating" was recognized and I could control the heating.

In the device list I have two devices now:
heating, WeMo Switch (which was the one created with echo dot 2)
heating, Belkin International Inc. intelligentes Gerät (created with the echo dot 3)

I was lucky and thought all works. Until I added a second device "lamp" to my Raspi where the echo dot 3 is located. As expected, this device was also recognized. But when I try to control that device, I get the answer "it is not supported" After I read about some issues with newer versions of echo dot 2, I've tried "ST: urn:Belkin:device:**", "ST: upnp:rootdevice" and "ST: ssdp:all" in the answer. All with the same result, the answer was "not supported"

Next I've tried to debug my program, why it works with "heating" but not with "lamp" I found out, that in case of "heating" not the Raspi on the local site of the echo dot 3 was contacted, but the one on the other site. This explains me, why it works.

Since both echo dots are registered on my account, have I somehow to split them and tell they are in different networks?

Does anyone has a hint, why I get "it is not supported"?

I've tried a bit more. Setup a second Alexa account. The problem is still there. The device is recognized, but always get the answer "lamp doesn't support that" Could it be that the device is no more a "WeMo switch"? I cannot find in the sources any place where this is referenced.

**Comment by n8henrie** [comment]
Please follow the issue template.

I don't know the first thing about C# and can't really help you with a different implementation; this is the right place to file issues about n8henrie/fauxmo, but not really the right place for much else. Sorry, not trying to be a jerk.

I recently got an Echo Dot 3, and n8henrie/fauxmo is discovering and interacting with devices as expected.

I'm closing but not locking the issue so conversation can continue here if you'd like, but I'm not sure what more I can do to help.

**Comment by Schwenkner** [comment]
Sure you cannot answer my questions according to C#. I'm able to code in several languages, Python C# and C++ among them. My implementtion is a C# porting of the fauxmo library for Arduino in C++. Since this library has the same problem as mine porting, I assume the problem in some changes in the echo dot 3 firmware. I have already seen different UDP answers between dot3 and dot2.

I've assumed, Arduino fauxmo has a similar implementation as yours, it seems not. Arduino switched from Belkin WeMo to Phillips Hue. But both do not work on Arduino. When you tell me, you have tried yours with echo dot 3, then I will check my differences (I've seen there are some).

But thanks for the statement, that you use echo dot 3 successful.

**Comment by n8henrie** [comment]
Definitely. Sorry to not be more help. Your English is very good, but I'm afraid I may not entirely understand, so if there's anything else I can do to help please let me know.
