### ISSUE TITLE
 wdt reset in esp8266

### ISSUE THREAD

**Issue by vslinuxdotnet** [n8henrie/fauxmo#69]
Hello,

I try to run fauxmo 3.1.0 with your code example on a esp8266 and I get wdt reset.
The Alexa android app find the device, but in the first communication, bang!
See the tty debug and the FAUXMO debug:

```
connected with Honeypot, channel 8
dhcp client start.....................................
ip:192.168.1.209,mask:255.255.255.0,gw:192.168.1.1

[WIFI] STATION Mode, SSID: Honeypot, IP address: 192.168.1.209
[FAUXMO] Enabled
[FAUXMO] UDP server started
[FAUXMO] Disabled
[FAUXMO] Enabled
[FAUXMO] UDP server started
[MAIN] Free heap: 46984 bytes
[FAUXMO] Client #0 connected

 ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt `reset`

```
I test old versions with the same result.
I also test with beta version of esp8266 2.5.0 B2 and stable 2.4.2
The OS that I use is Linux

Any idea what appends ?

Regards.

**Comment by n8henrie** [comment]
ESP8266 are sweet, but they have little to do with this repo, which is a Python project for running on an actual computer (not a microcontroller). Sorry!
