### ISSUE TITLE
UTF-8 devicename issue

### ISSUE THREAD

**Issue by tim15** [n8henrie/fauxmo#70]
- **Operating system and version**: gentoo
- **Python version**: Python 3.6.5
- **Fauxmo version** (`fauxmo --version`): v0.4.8
- **Echo device type** (e.g. Echo, Echo Plus, Dot):  Echo Dot

## My Issue
I used german "Umlaute" in config.json.
The device scan didn't discover these switches, because the header length is false.

To make it working change in protocols.py
- f'CONTENT-LENGTH: {len(xml)}',
+f'CONTENT-LENGTH: {len(xml.encode('utf-8'))}',

**Comment by n8henrie** [comment]
Good catch, thanks.

```python
In [1]: len("foo") == len("foo".encode('utf8'))
Out[1]: True

In [2]: len("füu") == len("füu".encode('utf8'))
Out[2]: False
```

If you're interested, I'd be happy to accept a PR (as long as it includes an additional test).

**Comment by n8henrie** [comment]
Fixed in https://github.com/n8henrie/fauxmo/commit/9f83e096836a39eb78cef00a98744359847ab27c, should be merged into master with the next release.
