### ISSUE TITLE
Can I change the invocation to "make" instead of "turn on"

### ISSUE THREAD

**Issue by temocastro** [n8henrie/fauxmo#74]
Can I change the invocation to "make" instead of "turn on"

- **Operating system and version**:
- **Python version**:
- **Fauxmo version** (`fauxmo --version`):
- **Echo device type** (e.g. Echo, Echo Plus, Dot): 
- **[Echo Firmware Version](https://github.com/n8henrie/fauxmo/blob/dev/README.md#troubleshooting--faq)**: 

## [WHYT](http://mattgemmell.com/what-have-you-tried)

---

Please make sure you've taken these steps before submitting a new issue:

- [ ] Try to reproduce the issue with Fauxmo installed in a
  [venv](https://docs.python.org/3/library/venv.html)
- [ ] Ensure you're running a supported version of Python
    - Requires Python >= 3.2 for Fauxmo < 0.3.0
    - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
    - Requires Python >= 3.6.0 for Fauxmo >= 0.4.0
- [ ] Run Fauxmo in debug mode (`-vvv`) and include relevant output
- [ ] Include your Fauxmo `config.json`
- [ ] Search the existing (including closed) issues
- [ ] Please use [codeblocks][1] around your debug output and config

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by n8henrie** [comment]
Nope, at least not directly (not anything I can control on the Fauxmo side).

However, you may be able to create a "Routine" using the Alexa app, where you "turn on" a Fauxmo switch and use a custom trigger phrase, and thereby achieve the same end result.
