### ISSUE TITLE
Error occured on Echo Spot after Webhook

### ISSUE THREAD

**Issue by eddie209** [n8henrie/fauxmo#75]
- **Operating system and version**: Raspian
- **Python version**: 3.6
- **Fauxmo version** (`fauxmo --version`): 0.4.8
- **Echo device type** (e.g. Echo, Echo Plus, Dot): Echo Spot
- **[Echo Firmware Version](https://github.com/n8henrie/fauxmo/blob/dev/README.md#troubleshooting--faq)**: 

## My Issue

I emulate a swith for opening / closing my Velux.
The Off button work correctly.
The On button function correctly but the Echo Spot said "an error occured". I think the problem come with the echo trying to have a status ?

Here is my config file : 
```json
"FAUXMO": {
        "ip_address": "auto"
    },
    "PLUGINS": {
        "SimpleHTTPPlugin": {
            "DEVICES": [
                {
                    "port": 12340,
                    "on_cmd": "https:/URL-TO-WEBHOOK-ON",
                    "off_cmd": "https:/URL-TO-WEBHOOK-OFF",
                    "state_response_off" : "Velux ferme",
                    "state_response_on" : "Velux ouvert",
                    "state_cmd": "FAKE RESPONSE SIMILAR TO END OF https://github.com/n8henrie/fauxmo/blob/master/protocol_notes.md",
                    "on_data": {"isOn": 1},
                    "off_data" : {"isOn": 0},
                    "method": "GET",
                    "name": "Volets"
                }
            ]
        }
    }
}
```

## [WHYT](http://mattgemmell.com/what-have-you-tried)

---

Please make sure you've taken these steps before submitting a new issue:

- [x] Try to reproduce the issue with Fauxmo installed in a
  [venv](https://docs.python.org/3/library/venv.html)
- [x] Ensure you're running a supported version of Python
    - Requires Python >= 3.2 for Fauxmo < 0.3.0
    - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
    - Requires Python >= 3.6.0 for Fauxmo >= 0.4.0
- [ ] Run Fauxmo in debug mode (`-vvv`) and include relevant output
- [x] Include your Fauxmo `config.json`
- [x] Search the existing (including closed) issues
- [ ] Please use [codeblocks][1] around your debug output and config

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by n8henrie** [comment]
Thanks for following most of the issue template, but you're missing the verbose log output, which is pretty critical. Please edit your issue to include this.

**Comment by n8henrie** [comment]
I haven't gotten a reply, so I'm closing this issue as dead. Please feel free to let me know if I should re-open.
