### ISSUE TITLE
please update documentation for use of simplehttpplugin

### ISSUE THREAD

**Issue by johngo7470** [n8henrie/fauxmo#81]
This is a request/reminder to look into why the documentation at https://fauxmo.readthedocs.io/en/latest/fauxmo.plugins.html#module-fauxmo.plugins.simplehttpplugin  seems to have not been updated.

**Comment by n8henrie** [comment]
https://fauxmo.readthedocs.io/en/latest/fauxmo.plugins.html#module-fauxmo.plugins.simplehttpplugin

Might need to refresh your browser cache to reflect the changes.
