### ISSUE TITLE
minor documentation update (troubleshooting)

### ISSUE THREAD

**Issue by johngo7470** [n8henrie/fauxmo#85]
In the protocol notes, you mentioned being able to get the IP address of the Echo, by searching for F0:27:2D, but seems there are more mac addresses that are possible. My Echo is at 18:74:2E:2E:CC:B6 

https://www.wireshark.org/tools/oui-lookup.html  shows that both are associated with Amazon. Probably many more...  

In my particular case, I went to my wifi router and looked for "Amazon..." devices in my wireless clients list, and although I have more than one Amazon device, it was a much smaller list of IP's to select from.

**Comment by n8henrie** [comment]
It looks like grepping for `Amazon` picks up a broad number of devices, presumably because nmap keeps an up-to-date mapping of MAC addresses to manufacturers (and seems reasonable to outsource this task to them, as it will likely continue to change in the future).
