### ISSUE TITLE
Fauxmo does not work with Home Assistant

### ISSUE THREAD

**Issue by ful4n1t0c0sme** [n8henrie/fauxmo#88]
- Issues not following the template may be closed for that reason alone.
- **Operating system and version**: Ubuntu Disco
- **Python version**: Venv version (Python 3.7 I think)
- **Fauxmo version** (`fauxmo --version`): Latest (0.49)
- **Echo device type** (e.g. Echo, Echo Plus, Dot):  Echo Dot v2
- **[Echo Firmware Version](https://github.com/n8henrie/fauxmo/blob/dev/README.md#troubleshooting--faq)**: Not important

## My Issue
Home Assistant found only one switch.

## [WHYT](http://mattgemmell.com/what-have-you-tried)
Switches are configured as follow:
wemo:
  static:
    - 192.168.0.204:50000
    - 192.168.0.204:50001
....
    - 192.168.0.204:50012

Please make sure you've taken these steps before submitting a new issue:

- [x] Try to reproduce the issue with Fauxmo installed in a
  [venv](https://docs.python.org/3/library/venv.html) DONE
- [x] Ensure you're running a supported version of Python DONE
    - Requires Python >= 3.2 for Fauxmo < 0.3.0
    - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
    - Requires Python >= 3.6.0 for Fauxmo >= 0.4.0
- [x] Run Fauxmo in debug mode (`-vvv`) and include relevant output DONE
- [x] Include your Fauxmo `config.json` Does not apply
- [x] Search the existing (including closed) issues DONE
- [x] Please use [codeblocks][1] around your debug output and config

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

It's a simple bug. Forgot to include                     "X-User-Agent: redsonic" on "protocols.py". If there is not X-User-Agent, Home Assistant cant found switches.

My modified code that works is this:

//---------CODE-FOLLOWS----------//

"""protocols.py :: Provide asyncio protocols for UPnP and SSDP discovery."""

import asyncio
import random
import uuid
from email.utils import formatdate
from typing import cast, Iterable, Text, Tuple, Union

from fauxmo import logger
from fauxmo.plugins import FauxmoPlugin
from fauxmo.utils import make_serial

class Fauxmo(asyncio.Protocol):
    """Mimics a WeMo switch on the network.

    Aysncio protocol intended for use with BaseEventLoop.create_server.
    """

    NEWLINE = "\r\n"

    def __init__(self, name: str, plugin: FauxmoPlugin) -> None:
        """Initialize a Fauxmo device.

        Args:
            name: How you want to call the device, e.g. "bedroom light"
            plugin: Fauxmo plugin
        """
        self.name = name
        self.serial = make_serial(name)
        self.plugin = plugin
        self.transport: asyncio.Transport = None

    def connection_made(self, transport: asyncio.BaseTransport) -> None:
        """Accept an incoming TCP connection.

        Args:
            transport: Passed in asyncio.Transport
        """
        peername = transport.get_extra_info("peername")
        logger.debug(f"Connection made with: {peername}")
        self.transport = cast(asyncio.Transport, transport)

    def data_received(self, data: bytes) -> None:
        """Decode incoming data.

        Args:
            data: Incoming message, either setup request or action request
        """
        msg = data.decode()

        logger.debug(f"Received message:\n{msg}")
        if msg.startswith("GET /setup.xml HTTP/1.1"):
            logger.info("setup.xml requested by Echo")
            self.handle_setup()
        elif "/eventservice.xml" in msg:
            logger.info("eventservice.xml request by Echo")
            self.handle_event()
        elif "/metainfoservice.xml" in msg:
            logger.info("metainfoservice.xml request by Echo")
            self.handle_metainfo()
        elif msg.startswith("POST /upnp/control/basicevent1 HTTP/1.1"):
            logger.info("request BasicEvent1")
            self.handle_action(msg)

    def handle_setup(self) -> None:
        """Create a response to the Echo's setup request."""
        setup_xml = (
            "<?xml version='1.0'?>"
            "<root xmlns='urn:Belkin:device-1-0'>"
            "<specVersion>"
            "<major>1</major>"
            "<minor>0</minor>"
            "</specVersion>"
            "<device>"
            "<deviceType>urn:Belkin:device:controllee:1</deviceType>"
            f"<friendlyName>{self.name}</friendlyName>"
            "<manufacturer>Belkin International Inc.</manufacturer>"
            "<manufacturerURL>http://www.belkin.com</manufacturerURL>"
            "<modelDescription>Belkin Plugin Socket 1.0</modelDescription>"
            "<modelName>Socket</modelName>"
            "<modelNumber>1.0</modelNumber>"
            "<modelURL>http://www.belkin.com/plugin/</modelURL>"
            f"<serialNumber>{self.serial}</serialNumber>"
            f"<UDN>uuid:Socket-1_0-{self.serial}</UDN>"
            "<UPC>123456789</UPC>"
            "<macAddress>94103E3489C0</macAddress>"
            "<firmwareVersion>WeMo_WW_2.00.8326.PVT-OWRT-SNS</firmwareVersion>"
            "<iconVersion>0|49153</iconVersion>"
            "<serviceList>"
            "<service>"
            "<serviceType>urn:Belkin:service:basicevent:1</serviceType>"
            "<serviceId>urn:Belkin:serviceId:basicevent1</serviceId>"
            "<controlURL>/upnp/control/basicevent1</controlURL>"
            "<eventSubURL>/upnp/event/basicevent1</eventSubURL>"
            "<SCPDURL>/eventservice.xml</SCPDURL>"
            "</service>"
            "<service>"
            "<serviceType>urn:Belkin:service:metainfo:1</serviceType>"
            "<serviceId>urn:Belkin:serviceId:metainfo1</serviceId>"
            "<controlURL>/upnp/control/metainfo1</controlURL>"
            "<eventSubURL>/upnp/event/metainfo1</eventSubURL>"
            "<SCPDURL>/metainfoservice.xml</SCPDURL>"
            "</service>"
            "</serviceList>"
            "</device>"
            "</root>"
        )

        setup_response = self.add_http_headers(setup_xml)
        logger.debug(f"Fauxmo response to setup request:\n{setup_response}")
        self.transport.write(setup_response.encode())
        self.transport.close()

    def handle_action(self, msg: str) -> None:
        """Execute `on`, `off`, or `get_state` method of plugin.

        Args:
            msg: Body of the Echo's HTTP request to trigger an action

        """
        logger.debug(f"Handling action for plugin type {self.plugin}")

        success = False
        soap_format = (
            "<?xml version='1.0' encoding='utf-8'?>"
            "<s:Envelope "
            'xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" '
            's:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">'
            "<s:Body>"
            "<u:{action}{action_type}Response "
            'xmlns:u="urn:Belkin:service:basicevent:1">'
            "<{action_type}>{return_val}</{action_type}>"
            "</u:{action}{action_type}Response>"
            "</s:Body>"
            "</s:Envelope>"
        ).format

        command_format = (
            'SOAPACTION: "urn:Belkin:service:basicevent:1#{}"'
        ).format

        soap_message: str = None
        action: str = None
        action_type: str = None
        return_val: str = None

        if command_format("GetBinaryState").casefold() in msg.casefold():
            logger.info(f"Attempting to get state for {self.plugin.name}")

            action = "Get"
            action_type = "BinaryState"

            try:
                state = self.plugin.get_state()
            except AttributeError:
                logger.warning(
                    f"Plugin {self.plugin.__module__} has not "
                    "implemented a `get_state` method."
                )
            else:
                logger.info(f"{self.plugin.name} state: {state}")

                success = True
                return_val = str(int(state.lower() == "on"))

        elif command_format("SetBinaryState").casefold() in msg.casefold():
            action = "Set"
            action_type = "BinaryState"

            if "<BinaryState>0</BinaryState>" in msg:
                logger.info(f"Attempting to turn off {self.plugin.name}")
                return_val = "0"
                success = self.plugin.off()

            elif "<BinaryState>1</BinaryState>" in msg:
                logger.info(f"Attempting to turn on {self.plugin.name}")
                return_val = "1"
                success = self.plugin.on()

            else:
                logger.warning(f"Unrecognized request:\n{msg}")

        elif command_format("GetFriendlyName").casefold() in msg.casefold():
            action = "Get"
            action_type = "FriendlyName"
            return_val = self.plugin.name
            success = True
            logger.info(f"{self.plugin.name} returning friendly name")

        if success:
            soap_message = soap_format(
                action=action, action_type=action_type, return_val=return_val
            )

            response = self.add_http_headers(soap_message)
            logger.debug(response)
            self.transport.write(response.encode())
        else:
            errmsg = (
                f"Unable to complete command for {self.plugin.name}:\n"
                f"{msg}"
            )
            logger.warning(errmsg)
        self.transport.close()

    def handle_metainfo(self) -> None:
        """Respond to request for metadata."""
        metainfo_xml = (
            '<scpd xmlns="urn:Belkin:service-1-0">'
            "<specVersion>"
            "<major>1</major>"
            "<minor>0</minor>"
            "</specVersion>"
            "<actionList>"
            "<action>"
            "<name>GetMetaInfo</name>"
            "<argumentList>"
            "<retval />"
            "<name>GetMetaInfo</name>"
            "<relatedStateVariable>MetaInfo</relatedStateVariable>"
            "<direction>in</direction>"
            "</argumentList>"
            "</action>"
            "</actionList>"
            "<serviceStateTable>"
            '<stateVariable sendEvents="yes">'
            "<name>MetaInfo</name>"
            "<dataType>string</dataType>"
            "<defaultValue>0</defaultValue>"
            "</stateVariable>"
            "</serviceStateTable>"
            "</scpd>"
        ) + 2 * Fauxmo.NEWLINE

        meta_response = self.add_http_headers(metainfo_xml)
        logger.debug(f"Fauxmo response to setup request:\n{meta_response}")
        self.transport.write(meta_response.encode())
        self.transport.close()

    def handle_event(self) -> None:
        """Respond to request for eventservice.xml."""
        eventservice_xml = (
            '<scpd xmlns="urn:Belkin:service-1-0">'
            "<actionList>"
            "<action>"
            "<name>SetBinaryState</name>"
            "<argumentList>"
            "<argument>"
            "<retval/>"
            "<name>BinaryState</name>"
            "<relatedStateVariable>BinaryState</relatedStateVariable>"
            "<direction>in</direction>"
            "</argument>"
            "</argumentList>"
            "</action>"
            "<action>"
            "<name>GetBinaryState</name>"
            "<argumentList>"
            "<argument>"
            "<retval/>"
            "<name>BinaryState</name>"
            "<relatedStateVariable>BinaryState</relatedStateVariable>"
            "<direction>out</direction>"
            "</argument>"
            "</argumentList>"
            "</action>"
            "</actionList>"
            "<serviceStateTable>"
            '<stateVariable sendEvents="yes">'
            "<name>BinaryState</name>"
            "<dataType>Boolean</dataType>"
            "<defaultValue>0</defaultValue>"
            "</stateVariable>"
            '<stateVariable sendEvents="yes">'
            "<name>level</name>"
            "<dataType>string</dataType>"
            "<defaultValue>0</defaultValue>"
            "</stateVariable>"
            "</serviceStateTable>"
            "</scpd>"
        ) + 2 * Fauxmo.NEWLINE

        event_response = self.add_http_headers(eventservice_xml)
        logger.debug(f"Fauxmo response to setup request:\n{event_response}")
        self.transport.write(event_response.encode())
        self.transport.close()

    @staticmethod
    def add_http_headers(xml: str) -> str:
        """Add HTTP headers to an XML body.

        Args:
            xml: XML body that needs HTTP headers
        """
        date_str = formatdate(timeval=None, localtime=False, usegmt=True)
        return (Fauxmo.NEWLINE).join(
            [
                "HTTP/1.1 200 OK",
                f'CONTENT-LENGTH: {len(xml.encode("utf8"))}',
                "CONTENT-TYPE: text/xml; charset='utf-8'",
                f"DATE: {date_str}",
            #    "LAST-MODIFIED: Sat, 01 Jan 2000 00:01:15 GMT",
                "SERVER: Unspecified, UPnP/1.0, Unspecified",
                "X-User-Agent: redsonic",
                f"CONNECTION: close{Fauxmo.NEWLINE}",
                f"{xml}",
            ]
        )

class SSDPServer(asyncio.DatagramProtocol):
    """UDP server that responds to the Echo's SSDP / UPnP requests."""

    def __init__(self, devices: Iterable[dict] = None) -> None:
        """Initialize an SSDPServer instance.

        Args:
            devices: Iterable of devices to advertise when the Echo's SSDP
                     search request is received.
        """
        self.devices = list(devices or ())

    def add_device(self, name: str, ip_address: str, port: int) -> None:
        """Keep track of a list of devices for logging and shutdown.

        Args:
            name: Device name
            ip_address: IP address of device
            port: Port of device
        """
        device_dict = {"name": name, "ip_address": ip_address, "port": port}
        self.devices.append(device_dict)

    def connection_made(self, transport: asyncio.BaseTransport) -> None:
        """Set transport attribute to incoming transport.

        Args:
            transport: Incoming asyncio.DatagramTransport
        """
        self.transport = cast(asyncio.DatagramTransport, transport)

    def datagram_received(
        self, data: Union[bytes, Text], addr: Tuple[str, int]
    ) -> None:
        """Check incoming UDP data for requests for Wemo devices.

        Args:
            data: Incoming data content
            addr: Address sending data
        """
        if isinstance(data, bytes):
            data = data.decode("utf8")

        logger.debug(f"Received data below from {addr}:")
        logger.debug(data)

        discover_patterns = [
            "ST: urn:Belkin:device:**",
            "ST: upnp:rootdevice",
            "ST: ssdp:all",
        ]

        discover_pattern = next(
            (pattern for pattern in discover_patterns if pattern in data), None
        )
        if (
            'man: "ssdp:discover"' in data.lower()
            and discover_pattern is not None
        ):
            mx = 0.0
            mx_line = next(
                (
                    line
                    for line in str(data).splitlines()
                    if line.startswith("MX: ")
                ),
                None,
            )
            if mx_line:
                mx_str = mx_line.split()[-1]
                if mx_str.replace(".", "", 1).isnumeric():
                    mx = float(mx_str)

            self.respond_to_search(addr, discover_pattern, mx)

    def respond_to_search(
        self, addr: Tuple[str, int], discover_pattern: str, mx: float = 0.0
    ) -> None:
        """Build and send an appropriate response to an SSDP search request.

        Args:
            addr: Address sending search request
        """
        date_str = formatdate(timeval=None, localtime=False, usegmt=True)
        for device in self.devices:

            name = device.get("name")
            ip_address = device.get("ip_address")
            port = device.get("port")

            location = f"http://{ip_address}:{port}/setup.xml"
            serial = make_serial(name)
            usn = (
                f"uuid:Socket-1_0-{serial}::"
                f'{discover_pattern.lstrip("ST: ")}'
            )

            response = (Fauxmo.NEWLINE).join(
                [
                    "HTTP/1.1 200 OK",
                    "CACHE-CONTROL: max-age=86400",
                    f"DATE: {date_str}",
                    "EXT:",
                    f"LOCATION: {location}",
                    'OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01',
                    f"01-NLS: {uuid.uuid4()}",
                    "SERVER: Unspecified, UPnP/1.0, Unspecified",
                    "X-User-Agent: redsonic"
                    f"{discover_pattern}",
                    f"USN: {usn}",
                ]
            ) + (2 * Fauxmo.NEWLINE)
            asyncio.ensure_future(
                self._send_async_response(response.encode("utf8"), addr, mx)
            )

    async def _send_async_response(
        self, response: bytes, addr: Tuple[str, int], mx: float = 0.0
    ) -> None:
        logger.debug(f"Sending response to {addr} with mx {mx}:\n{response}")
        await asyncio.sleep(random.random() * max(0, min(5, mx)))
        self.transport.sendto(response, addr)

    def connection_lost(self, exc: Exception) -> None:
        """Handle lost connections.

        Args:
            exc: Exception type
        """
        if exc:
            logger.warning(f"SSDPServer closed with exception: {exc}")

//------------CODE-END-------//

**Comment by n8henrie** [comment]
I didn't "forget" that user agent, I intentionally set it to something unique to make it easier for users to identify connections from Fauxmo.

HomeAssistant is *much* more powerful than Fauxmo -- they're not even in the same class -- so I have it run all of the switches and automations primarily, which Fauxmo then accesses by way of the HomeAssistantPlugin (in dev branch, hopefully getting merged soon).

Tell me more about your use case? This is backwards from how I'm doing things, and I don't see why you'd want to do it this way -- what are you setting up in Fauxmo that you want to expose to HomeAssistant, instead of setting it up in HomeAssistant and exposing to Fauxmo?

EDIT: 

> Home Assistant found only one switch.

Did it find one switch without the User Agent change? If so, the user agent seems unlikely to be the problem (seems like it should find none if that were the case).

**Comment by ful4n1t0c0sme** [comment]
You intentionally set it to something unique to make it easier for users to
identify connections from Fauxmo. I understand that. But in this case, Home
Assistant only detect one of the fauxmo emulated switches.

With the correct User Agent, Home Assistant found all the fauxmo switches.
With your code (nop User Agent) only found the first. I reported the bug
and I give to you the solution.

Sorry for my terrible english.

**Comment by ful4n1t0c0sme** [comment]
Fauxmo works pretty well for this propose (fake Wemo switches to be picked
up by an Amazon Echo). Really good and fast response. I think Echo is easy
to cheat for that. But this can change in a future upgrade of the Echo
firmware. If Amazon launch an upgraded firmware that search for User Agent
(like Home Assistant) in the future, Fauxmo will stop working.

With the User Agent added to the code, Echo continue to work ok with
Fauxmo, and begin to work with Home Assistant too. Think this like an
"upgrade". Fauxmo can work now emulating switches for the Amazon Echo and
now (with  and via Home Assistant) can work with Google Home too.


I have Home Assistant running in the same PC (old Atom processor with 1GB
ram with Ubuntu) than Fauxmo switches. Fauxmo emulate Wemo devices and
switch relays via Parallel Port. Switches are discovered now by Home
Assistant and with the integration of Amazon Alexa and Google Home, I can
turn on and off all the Fauxmo (via LPT port) switches with the tree
devices.

I can say "Alexa, turn on(or off) kitchen lights" and "Ok, Google, turn on
(or off) kitchen light". I can turn on and off all the switches via Alexa
App on any phone, or via alexa.amazon.com, or via my own web implementation
too. Or vía Home Assistant too.

**Comment by ful4n1t0c0sme** [comment]
I talk about the complet project, not only the config file. I think you can
use some ideas from this.

**Comment by n8henrie** [comment]
I don't think it has anything to do with the user-agent, I think it's because you added `serialNumber`, and currently [HomeAssistant filters duplicate devices by serial number](https://github.com/home-assistant/home-assistant/blob/7b86f0f9265dc8cdcf7ed92c0db7340604134569/homeassistant/components/wemo/__init__.py#L166).

That's why your issue didn't make any sense, and likely why I've been unable to reproduce it locally.

Feel free to make a pull request against the dev branch that adds the `serialnumber`. While I previously used the `name` to make the UDN, I would think using a combination of the host + port might make a better unique serial number than the name. Or perhaps a combination of all 3.

**Comment by ful4n1t0c0sme** [comment]
I tested everything. Serial number does not make any difference. (Alexa
found all the switches and Home Assistant only the first one). I simple
leave it because is more similar that way only to the response of a real
Wemo. Home Assistant only found all the switches when I add the User Agent
line. If I quit the serial number in the code, the response is the same
(Fauxmo working ok on Alexa but only the first switch found in Home
Assistant).

I try running the same (Home Assistant and Fauxmo) on a Raspberry PI with
Raspbian and the result is the same than in the Atom computer with Ubuntu.
Home Assistant only found all the switches only if I put the User Agent
line.
 I only change the scrypt that make use of LPT for GPIO only. All the code
is the same in both computers. Like you, I think that is not a real bug,
but is a nice feature to support Home Assistant and Alexa than only Alexa.
More because the only change is add a single line of code.

Really thanks for your time and happy to say to you that your work is
excelent. Remember. If you like, I can share all my project with you. Is in
development for now, but it's working.

**Comment by n8henrie** [comment]
Thanks for your kind words.

I'm afraid I can't reproduce your findings.

By adding just `f"<serialNumber>{self.serial}</serialNumber>"` and absolutely nothing else I can get homeassistant to pick up 3 Fauxmo devices, and I can confirm that they work when toggled through HomeAssistant.

I'm going to add this change to a feature branch: `issue_88`. Please install from this branch and see if it fixes your use case.

Again, your config would be helpful here.

**Comment by n8henrie** [comment]
Bump.

This issue is pending a response and is blocked until I have more info. To keep the issue list groomed, I will often close these stalled issues if they go a prolonged time without a response. In this case, I will give it another week or so.
