### ISSUE TITLE
asyncio:1608     ERROR    Fatal error: protocol.data_received() call failed.

### ISSUE THREAD

**Issue by rudiratlos** [n8henrie/fauxmo#93]
get every 10 secs these entries in syslog:
rpi4 with Linux pump 4.19.93-v7l+ #1290 SMP Fri Jan 10 16:45:11 GMT 2020 armv7l GNU/Linux

Jan 30 17:01:37 pump fauxmo[5337]: 2020-01-30 17:01:37 asyncio:1608     ERROR    Fatal error: protocol.data_received() call failed.
Jan 30 17:01:37 pump fauxmo[5337]: protocol: 
Jan 30 17:01:37 pump fauxmo[5337]: transport: <_SelectorSocketTransport fd=18 read=polling write=>
Jan 30 17:01:37 pump fauxmo[5337]: Traceback (most recent call last):
Jan 30 17:01:37 pump fauxmo[5337]:   File "/opt/pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 1317, in do_open
Jan 30 17:01:37 pump fauxmo[5337]:     encode_chunked=req.has_header('Transfer-encoding'))
Jan 30 17:01:37 pump fauxmo[5337]:   File "/opt/pyenv/versions/3.7.3/lib/python3.7/http/client.py", line 1229, in request
Jan 30 17:01:37 pump fauxmo[5337]:     self._send_request(method, url, body, headers, encode_chunked)
Jan 30 17:01:37 pump fauxmo[5337]:   File "/opt/pyenv/versions/3.7.3/lib/python3.7/http/client.py", line 1275, in _send_request
Jan 30 17:01:37 pump fauxmo[5337]:     self.endheaders(body, encode_chunked=encode_chunked)
Jan 30 17:01:37 pump fauxmo[5337]:   File "/opt/pyenv/versions/3.7.3/lib/python3.7/http/client.py", line 1224, in endheaders
Jan 30 17:01:37 pump fauxmo[5337]:     self._send_output(message_body, encode_chunked=encode_chunked)
Jan 30 17:01:37 pump fauxmo[5337]:   File "/opt/pyenv/versions/3.7.3/lib/python3.7/http/client.py", line 1016, in _send_output
Jan 30 17:01:37 pump fauxmo[5337]:     self.send(msg)
Jan 30 17:01:37 pump fauxmo[5337]:   File "/opt/pyenv/versions/3.7.3/lib/python3.7/http/client.py", line 956, in send
Jan 30 17:01:37 pump fauxmo[5337]:     self.connect()
Jan 30 17:01:37 pump fauxmo[5337]:   File "/opt/pyenv/versions/3.7.3/lib/python3.7/http/client.py", line 928, in connect
Jan 30 17:01:37 pump fauxmo[5337]:     (self.host,self.port), self.timeout, self.source_address)
Jan 30 17:01:37 pump fauxmo[5337]:   File "/opt/pyenv/versions/3.7.3/lib/python3.7/socket.py", line 727, in create_connection
Jan 30 17:01:37 pump fauxmo[5337]:     raise err
Jan 30 17:01:37 pump fauxmo[5337]:   File "/opt/pyenv/versions/3.7.3/lib/python3.7/socket.py", line 716, in create_connection
Jan 30 17:01:37 pump fauxmo[5337]:     sock.connect(sa)
Jan 30 17:01:37 pump fauxmo[5337]: ConnectionRefusedError: [Errno 111] Connection refused
Jan 30 17:01:37 pump fauxmo[5337]: During handling of the above exception, another exception occurred:
Jan 30 17:01:37 pump fauxmo[5337]: Traceback (most recent call last):
Jan 30 17:01:37 pump fauxmo[5337]:   File "/opt/pyenv/versions/3.7.3/lib/python3.7/asyncio/selector_events.py", line 813, in _read_ready__data_received
Jan 30 17:01:37 pump fauxmo[5337]:     self._protocol.data_received(data)
Jan 30 17:01:37 pump fauxmo[5337]:   File "/opt/pyenv/versions/3.7.3/lib/python3.7/site-packages/fauxmo/protocols.py", line 64, in data_received
Jan 30 17:01:37 pump fauxmo[5337]:     self.handle_action(msg)
Jan 30 17:01:37 pump fauxmo[5337]:   File "/opt/pyenv/versions/3.7.3/lib/python3.7/site-packages/fauxmo/protocols.py", line 143, in handle_action
Jan 30 17:01:37 pump fauxmo[5337]:     state = self.plugin.get_state()
Jan 30 17:01:37 pump fauxmo[5337]:   File "/opt/pyenv/versions/3.7.3/lib/python3.7/site-packages/fauxmo/plugins/simplehttpplugin.py", line 179, in get_state
Jan 30 17:01:37 pump fauxmo[5337]:     with self.urlopen(req) as resp:
Jan 30 17:01:37 pump fauxmo[5337]:   File "/opt/pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 222, in urlopen
Jan 30 17:01:37 pump fauxmo[5337]:     return opener.open(url, data, timeout)
Jan 30 17:01:37 pump fauxmo[5337]:   File "/opt/pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 525, in open
Jan 30 17:01:37 pump fauxmo[5337]:     response = self._open(req, data)
Jan 30 17:01:37 pump fauxmo[5337]:   File "/opt/pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 543, in _open
Jan 30 17:01:37 pump fauxmo[5337]:     '_open', req)
Jan 30 17:01:37 pump fauxmo[5337]:   File "/opt/pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 503, in _call_chain
Jan 30 17:01:37 pump fauxmo[5337]:     result = func(*args)
Jan 30 17:01:37 pump fauxmo[5337]:   File "/opt/pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 1345, in http_open
Jan 30 17:01:37 pump fauxmo[5337]:     return self.do_open(http.client.HTTPConnection, req)
Jan 30 17:01:37 pump fauxmo[5337]:   File "/opt/pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 1319, in do_open
Jan 30 17:01:37 pump fauxmo[5337]:     raise URLError(err)
Jan 30 17:01:37 pump fauxmo[5337]: urllib.error.URLError:

**Comment by n8henrie** [comment]
> - Issues not following the template may be closed for that reason alone.

I can't help much based on the information provided. I'm guessing your issue is based on a problem in your SimpleHTTPPlugin configuration, based on this: `Jan 30 17:01:37 pump fauxmo[5337]: ConnectionRefusedError: [Errno 111] Connection refused`

Please edit your issue to include the information requested in the issue template and I'll be happy to re-open.
