### ISSUE TITLE
Aaaargh!  I'm not sure what went wrong!!  REALLY!!!

### ISSUE THREAD

**Issue by ripface** [n8henrie/fauxmo#94]
Raspian Buster
Python3 3.7.3 (.venv)
Fauxmo v0.5.0 (-dev)
Echo Dot
Latest updates

## My Issue

I rebuilt my trusty raspberry pi after dear old SSE spiked half the computer devices in the house.

Bought a new Pi 3b and loaded up with the latest Buster, latest updates, latest Fauxmo-dev v0.5.0 from GIT.

All configured up with my Energenie IR daughterboard, sitting under our electric bed to control the head up/ legs down/ bedside lights/ massage unit.  Funcy eh?

Now, the new pi works fine, and I can control all the functions pretty well seamlessly.

Alexa on the other hand has a problemette.  Although she can control everything as expected I now get "I'm not sure what went wrong" after *every* command ... even though the command works.

I had a similar problem last year which was happily resolved by moving to the -dev branch and implementing the new "use_fake_state" option.

I've tried both the latest v0.5.0 and the DEV branch and nothing now seems to resolve the issue.

Can anyone help, it's driving me to distraction.

I have three raspberry PI's round the house to control various things from my garage doors to the mood lights in the kitchen.  All work well .... BAR the damn pi5 in the bedroom.

Nadgers!!

**Comment by n8henrie** [comment]
> All configured up with my Energenie IR daughterboard, sitting under our electric bed to control the head up/ legs down/ bedside lights/ massage unit. Funcy eh?

Nice!

Please use the template that should have been populated when you created this issue or pull request. I've taken a modest amount of time to set it up so that it requests the information necessary for me and mothers to be able to help, and frankly it's frustrating when users ignore it, delete it, or leave out requested details.

I'll leave this open for a week or so, but after that I think it's in everyone's best interest to close if you haven't been able to follow the template. Not trying to be unhelpful here; we can re-open at any time if the missing information is provided, but you have to help me help you.

**Comment by ripface** [comment]
Hey Nathan,

Thanks for getting back to me.  I thought I'd added all the relevant info from the template at the very top of my post.  Did I miss something?

As it happens, the issue has not gone away ... but seems to have got bored of reminding me that Alexa is "not sure what went wrong!".  I get this from Alexa once or twice a week now, but the rest of the time the control via fauxmo works flawlessly.

This is actually more frustrating as it means I can't reproduce the issue at will, which in turn makes troubleshooting almost impossible.  I can live with this! 

Please feel free to close this ticket.  I really appreciate the time and effort you must put into supporting this.  As a veteran of IT support for 40+ years I feel your pain!

Thanks,
John.

**Comment by n8henrie** [comment]
>  I thought I'd added all the relevant info from the template at the very top of my post.

Not even close :) You missed the last half of the template: 

> ## [WHYT](http://mattgemmell.com/what-have-you-tried)
> 
> 
> 
> ---
> 
> Please make sure you've taken these steps before submitting a new issue:
> 
> - [ ] Try to reproduce the issue with Fauxmo installed in a
>   [venv](https://docs.python.org/3/library/venv.html)
> - [ ] Ensure you're running a supported version of Python
>     - Requires Python >= 3.2 for Fauxmo < 0.3.0
>     - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
>     - Requires Python >= 3.6.0 for Fauxmo >= 0.4.0
> - [ ] Run Fauxmo in debug mode (`-vvv`) and include relevant output
> - [ ] Include your Fauxmo `config.json`
> - [ ] Search the existing (including closed) issues
> - [ ] Please use [codeblocks][1] around your debug output and config
> 
> [1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

---

> This is actually more frustrating as it means I can't reproduce the issue at will, which in turn makes troubleshooting almost impossible.

This issues are tough, and frankly they seem really common when dealing with Alexa.

If you do happen to catch one and can post the verbose logs of the interaction that may be interesting.

One other thing that (sometimes?) seems to help is having Alexa forget all devices and then re-adding them. There seems to be some kind of caching going on behind the scenes that I don't totally understand (i.e. I've had Alexa re-add Fauxmo devices that don't really exist when Fauxmo wasn't running).

> Please feel free to close this ticket.

Thanks for the quick and polite responses. Please let me know if the problems return / worsen and you want me to reopen.
